### ISSUE TITLE
error starting the traccar-server v3.0

### ISSUE THREAD

**Issue by guilhermesouza** [traccar/traccar#1274]
error starting the traccar-server v3.0
```
STATUS | wrapper  | 2015/06/26 21:30:49 | Launching a JVM...
INFO   | jvm 1    | 2015/06/26 21:30:50 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error: org.postgresql.util.PSQLException: ERROR: syntax error at or near "user"
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   Position: 14
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:562)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.traccar.database.QueryBuilder.executeUpdate(QueryBuilder.java:411)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:160)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:115)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:26)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/06/26 21:30:51 | WrapperSimpleApp Error:   at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2015/06/26 21:30:53 | <-- Wrapper Stopped
```
tail -100f tracker-server.log
```
2015-06-26 21:11:30  WARN: ERROR: syntax error at or near "RETURNING"
  Position: 20 - PSQLException (... < QueryBuilder.java:287 < DataManager.java:225 < PermissionsManager.java:50 < ...)
2015-06-26 21:30:51  WARN: ERROR: syntax error at or near "RETURNING"
  Position: 20 - PSQLException (... < QueryBuilder.java:287 < DataManager.java:225 < PermissionsManager.java:50 < ...)
```

**Comment by tananaev** [comment]
Are you using PostgreSQL? If yes, you need to modify the config file.

**Comment by guilhermesouza** [comment]
Yes, PostgreSQL. 
I've done the traccar.xml configuration by entering the connection data to PostgreSQL database.

**Comment by guilhermesouza** [comment]
My config.

    

    <entry key='database.driver'>org.postgresql.Driver</entry>
    <entry key='database.driverFile'>/opt/traccar/lib/postgresql-9.3-1103-jdbc4.jar</entry>
    <entry key='database.dataSource'>org.postgresql.ds.PGSimpleDataSource</entry>
    <entry key='database.url'>jdbc:postgresql://127.0.0.1:5432/traccar</entry>
    <entry key='database.user'>traccar</entry>
    <entry key='database.password'>traccar</entry>
    <entry key='database.checkTable'>traccar</entry>

**Comment by guilhermesouza** [comment]
I need to re-create the tables as <entry key = "database.createSchema '> PostgreSQL standard?

**Comment by tananaev** [comment]
You need to update SQL queries in the config.
