### ISSUE TITLE
IOException (SocketDispatcher.java:43)

### ISSUE THREAD

**Issue by wahisoufiane** [traccar/traccar#1355]
Hi,

I've this issue sometimes, without any reason, it appears, and disappears :

<pre>java.io.IOException: An established connection was aborted by the software in your host machine
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)</pre>

**Comment by tananaev** [comment]
Please provide more details. Are you using default version of Traccar with default config? Which version? How many devices do you have? Where do you see this error message?

**Comment by wahisoufiane** [comment]
I'm using version 2.12, I didn't modify the default config, but some queries and filters. I'm testing with one virtual device using (PacketSender) and have this error just before closing connections.

**Comment by tananaev** [comment]
Version 2.12 is quite old. I have fixed a lot of issues since then.

So, where do see get this error?

**Comment by wahisoufiane** [comment]
It's a Log.warranty in the StandardLoggingHandler in BasePipelineFactory.

**Comment by tananaev** [comment]
Do you mean `tracker-server.log`? It doesn't look like it.

**Comment by wahisoufiane** [comment]
yes, it doesn't look like it because I have added this line, to know the source of problem :
                event.getCause().printStackTrace();
but what I get in the log is : 
2015-08-13 11:46:29  WARN: An established connection was aborted by the software in your host machine - java.io.IOException (SocketDispatcher.java:-2)

**Comment by tananaev** [comment]
So you are not actually using version 2.12. You are using your custom build. Are you running it from IDE or using Java Service Wrapper?

**Comment by wahisoufiane** [comment]
I'm in Eclipse actually.

**Comment by tananaev** [comment]
Try to install official 2.12 (or newer) release and see if the same error happens there.

**Comment by wahisoufiane** [comment]
I have the official 2.12, I'll try if 3.0 still have the error. The think is that whether this error exist, My packet is decoded and persisted correctly, I'm just afraid that this will cause some issues.

**Comment by tananaev** [comment]
What I mean is that you need to try to install it as a service and not running it from Eclipse.
