### ISSUE TITLE
Clean install with mysql/mariadb

### ISSUE THREAD

**Issue by 1sthandy** [traccar/traccar#1643]
Hi,
i have this error on my synology with mariadb : 
- i want to build a new installation
- update a old db works, only admin/password login fails 

```
STATUS | wrapper  | 2016/01/06 18:37:30 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/01/06 18:37:30 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2016/01/06 18:37:30 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/01/06 18:37:30 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/01/06 18:37:30 | 
STATUS | wrapper  | 2016/01/06 18:37:30 | Launching a JVM...
INFO   | jvm 1    | 2016/01/06 18:37:30 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/01/06 18:37:31 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/01/06 18:37:31 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/01/06 18:37:34 | INFO 1/6/16 6:37 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/01/06 18:37:36 | INFO 1/6/16 6:37 PM: liquibase: Reading from traccar.DATABASECHANGELOG
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | WARNING 1/6/16 6:37 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/06 18:37:37 | SEVERE 1/6/16 6:37 PM: liquibase: /volume1/@appstore/traccar/data/db.changelog-master.xml: /volume1/@appstore/traccar/data/db.changelog-3.0.xml::changelog-3.0::author: Change Set /volume1/@appstore/traccar/data/db.changelog-3.0.xml::changelog-3.0::author failed.  Error: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE traccar.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/06 18:37:37 | liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE traccar.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.Liquibase.update(Liquibase.java:212)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:169)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at java.lang.reflect.Method.invoke(Method.java:497)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 18:37:37 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
INFO   | jvm 1    | 2016/01/06 18:37:37 |   ... 20 more
INFO   | jvm 1    | 2016/01/06 18:37:37 | INFO 1/6/16 6:37 PM: liquibase: /volume1/@appstore/traccar/data/db.changelog-3.0.xml::changelog-3.0::author: Successfully released change log lock
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set /volume1/@appstore/traccar/data/db.changelog-3.0.xml::changelog-3.0::author:
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE traccar.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:590)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:212)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:169)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Method.java:497)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error: Caused by: liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE traccar.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   ... 15 more
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
INFO   | jvm 1    | 2016/01/06 18:37:37 | WrapperSimpleApp Error:   ... 20 more
STATUS | wrapper  | 2016/01/06 18:37:39 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Looks like MariaDB doesn't support long keys:
```
Specified key was too long; max key length is 767 bytes
```

The only option I can think of is reduce the length of the fields in the changelog.

**Comment by 1sthandy** [comment]
if i change the character set from utf8 to latin1 it works
is it possible for you to change the fields in the changelog?

**Comment by tananaev** [comment]
I can't change them because current values are required for automatic updates from old versions.

**Comment by 1sthandy** [comment]
ok, can i use character latin1 for the mysql database?

**Comment by tananaev** [comment]
I haven't tried it.

**Comment by 1sthandy** [comment]
i build new packages for synology and i hope it works with latin1

**Comment by tananaev** [comment]
Let me know if it doesn't and I'll investigate the problem.

**Comment by 1sthandy** [comment]
The Problem is, that there is no way to update from Version 2, because the Database is UTF8, so old Data can not migrate. The only way is at the Moment to delete the Database and create the new one in Latin1 character.

**Comment by tananaev** [comment]
Not sure what can be done about it. I think we just need to draw the line somewhere and say that it's not possible to automatically upgrade.

**Comment by gmoscalu** [comment]
Guys, I hit the same issue today when upgrading, and i got rid of the error message by 

ALTER DATABASE traccar
    DEFAULT CHARACTER SET latin1
    DEFAULT COLLATE latin1_swedish_ci;

Afterwards, since it was all a mess and did not know what tables to drop to resume the upgrade, i renamed the DB & did a fresh install. Now I have another issue, for which i created https://github.com/tananaev/traccar/issues/1683, but that's a different story.

Gabriel

**Comment by gmoscalu** [comment]
Another option I saw on forums is to limit the length of the index - the email index was failing, so adding the 255 limit in the email length should cover 99% of use cases.

Meaning, the create table DDL:
   UNIQUE(email)
should be:
   UNIQUE(email(255))

**Comment by tananaev** [comment]
I think I need to start from scratch with the database script. There are too many issues with current upgrades.
