### ISSUE TITLE
Username is already taken (When adding user from admin login)

### ISSUE THREAD

**Issue by renattto** [traccar/traccar#1724]
Hi everyone,
I'm trying the new WebUI building for Traccar 3.3 on linux / mysql and everything is working. (the issue #510 helped me out with the only problem I had)
Now I'm trying to register users from an admin account on Settings/Users. (Register button on login disabled) Every random attempt I get a "Username is already taken" error.

from traccar console i get:

```
jvm 1    | [qtp12414878-41] WARN / - Exception while dispatching incoming RPC call
jvm 1    | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.addUser(org.traccar.web.shared.model.User) throws org.traccar.web.shared.model.InvalidMaxDeviceNumberForUserException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
jvm 1    |  at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
jvm 1    |  at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
jvm 1    |  at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
jvm 1    |  at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
jvm 1    |  at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
jvm 1    |  at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
jvm 1    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
jvm 1    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
jvm 1    |  at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
jvm 1    |  at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
jvm 1    |  at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
jvm 1    |  at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
jvm 1    |  at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
jvm 1    |  at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
jvm 1    |  at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
jvm 1    |  at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
jvm 1    |  at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
jvm 1    |  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
jvm 1    |  at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
jvm 1    |  at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
jvm 1    |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
jvm 1    |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
jvm 1    |  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
jvm 1    |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
jvm 1    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
jvm 1    |  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
jvm 1    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
jvm 1    |  at org.eclipse.jetty.server.Server.handle(Server.java:499)
jvm 1    |  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
jvm 1    |  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
jvm 1    |  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
jvm 1    |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
jvm 1    |  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
jvm 1    |  at java.lang.Thread.run(Thread.java:745)
jvm 1    | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
jvm 1    |  at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
jvm 1    |  at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
jvm 1    |  at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
jvm 1    |  at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187)
jvm 1    |  at org.traccar.web.server.model.DataServiceImpl.addUser(DataServiceImpl.java:241)
jvm 1    |  at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
jvm 1    |  at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
jvm 1    |  at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
jvm 1    |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
jvm 1    |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |  at java.lang.reflect.Method.invoke(Method.java:606)
jvm 1    |  at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
jvm 1    |  ... 42 more
jvm 1    | Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
jvm 1    |  at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
jvm 1    |  at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
jvm 1    |  at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
jvm 1    |  at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
jvm 1    |  at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
jvm 1    |  at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
jvm 1    |  at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
jvm 1    |  at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)
jvm 1    |  at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)
jvm 1    |  at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:490)
jvm 1    |  at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:195)
jvm 1    |  at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:179)
jvm 1    |  at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:214)
jvm 1    |  at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
jvm 1    |  at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
jvm 1    |  at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
jvm 1    |  at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
jvm 1    |  at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
jvm 1    |  at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
jvm 1    |  at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
jvm 1    |  at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
jvm 1    |  at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
jvm 1    |  at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
jvm 1    |  at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
jvm 1    |  at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
jvm 1    |  ... 51 more
jvm 1    | Caused by: java.sql.SQLException: Field 'name' doesn't have a default value
jvm 1    |  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
jvm 1    |  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
jvm 1    |  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
jvm 1    |  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
jvm 1    |  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
jvm 1    |  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
jvm 1    |  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
jvm 1    |  at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
jvm 1    |  at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
jvm 1    |  at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
jvm 1    |  at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
jvm 1    |  at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
jvm 1    |  at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
jvm 1    |  ... 72 more
```

Any help is welcome.

**Comment by tananaev** [comment]
It looks like the problem is with web UI (possibly configuration issue). @vitalidze might be able to help here.

**Comment by renattto** [comment]
Thank you Tananaev.
Posted on wrong repository! (too many windows opened...)
Can this issue stay open? or better close and open a new one on  @vitalidze  traccar-web repository?

Sorry for taking your time! (and congrats for the great work!)

**Comment by tananaev** [comment]
We can keep this one open if you want.

**Comment by vitalidze** [comment]
@renattto Try following instructions from https://github.com/vitalidze/traccar-web/issues/519 as well.

**Comment by renattto** [comment]
thank you very much Vitaly. worked like a charm.
I've just missed this issue. =/ will look better next time before posting.

Just one curiosity, the snap to road function still not full implemented, is it?

Thanks again.

**Comment by vitalidze** [comment]
@renattto there is a restriction from data provider - maximum 100 points in a track. If you have less than that number of points then it will work for you.

**Comment by SebastEnn** [comment]
Issue got resolved. Can be closed.
