### ISSUE TITLE
Group devices [New feature request]

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#1832]
Group the devices into groups for better organization;

> **table "groups"** (register groups):
> - id
> - description
> - name
> 
> **table "devices"**:
> - id
> - group_id (foreach key)
> - **_other table fields_**

![print](https://cloud.githubusercontent.com/assets/8257020/14115246/995599e4-f5b0-11e5-9331-8b584b886280.jpg)

**Comment by glbatistabh** [comment]
I'm running the version 3.4 and is not available/visible.

**Comment by tananaev** [comment]
It's not released yet, but it's already implemented. It will be included in the next official release.

**Comment by glbatistabh** [comment]
There is a version of "build-dev" to download?

_You can close the topic._

**Comment by tananaev** [comment]
There is no dev build, but you can build a version from source if you want:

https://www.traccar.org/build/

**Comment by glbatistabh** [comment]
help! Error in "start"

```
git clone https://github.com/tananaev/traccar.git

./setup/package.sh 3.5.dev
unzip setup/traccar-linux-64-3.5.dev.zip
./traccar.run

/opt/traccar/bin/traccar start 
Starting traccar...
Waiting for traccar.....
WARNING: traccar may have failed to start.
```

```
cat /opt/traccar/logs/wrapper.log.20160329 
STATUS | wrapper  | 2016/03/29 18:32:55 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/03/29 18:32:55 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2016/03/29 18:32:55 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/03/29 18:32:55 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/03/29 18:32:55 | 
STATUS | wrapper  | 2016/03/29 18:32:56 | Launching a JVM...
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager: WARNING - The Wrapper jar file currently in use is version "3.5.28"
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager:           while the version of the Wrapper which launched this JVM is
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager:           "3.5.27".
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager:           The Wrapper may appear to work correctly but some features may
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager:           not function correctly.  This configuration has not been tested
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager:           and is not supported.
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager: 
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperSimpleApp Error: Unable to locate the class org.traccar.Main : java.lang.ClassNotFoundException: org.traccar.Main
INFO   | jvm 1    | 2016/03/29 18:32:56 | 
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperSimpleApp Usage:
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: Error in WrapperListener.start callback.  java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.text.MessageFormat.<init>(MessageFormat.java:362)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.text.MessageFormat.format(MessageFormat.java:840)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperResources.getString(WrapperResources.java:194)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.showUsage(WrapperSimpleApp.java:597)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.start(WrapperSimpleApp.java:441)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperManager$10.run(WrapperManager.java:4241)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: Caused by: java.lang.NumberFormatException: For input string: "app_class{/app_method}"
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.lang.Integer.parseInt(Integer.java:580)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.lang.Integer.parseInt(Integer.java:615)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
INFO   | jvm 1    | 2016/03/29 18:32:56 | WrapperManager Error: 	... 7 more
STATUS | wrapper  | 2016/03/29 18:32:57 | <-- Wrapper Stopped

```

**Comment by tananaev** [comment]
First of all, you need to remove old version of Traccar before installing a new one. Also, I guess something has failed during packaging. Look for any warnings or error messages.

**Comment by SebastEnn** [comment]
Feature implemented. Issue can be closed.
