### ISSUE TITLE
Looping code if id=groupid 

### ISSUE THREAD

**Issue by shuricksumy** [traccar/traccar#1910]
1. Log in as admin
2. On WI create group set name "Default".
3. Edit this Group and set Group "Default". See screenshot.
4. Restart server.

Actual result: server is not started due to loop in code

```
 org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
        at org.traccar.database.GroupTree.getNodes(GroupTree.java:145)
```

Expected result: should be validation on web to avoid such group combinations (id = groupid).

``` sql
mysql> select * from groups;
+----+---------+---------+
| id | name    | groupid |
+----+---------+---------+
|  1 | Default |       1 |
+----+---------+---------+
1 row in set (0,00 sec)
```

![validationid](https://cloud.githubusercontent.com/assets/12009686/14851214/1756f94a-0c87-11e6-937a-048bec3e7229.png)

**Comment by tananaev** [comment]
This issue has been already fixed.

**Comment by SebastEnn** [comment]
Since it has been fixed, this issue can be closed.
