### ISSUE TITLE
SEVERE: Error during scheduled task execution (after update)

### ISSUE THREAD

**Issue by ReabRed** [traccar/traccar#1977]
Hello,

i have update from 3.2 to 3.5 with your last version from -> tananaev/traccar
now i get all houer a RPC call error.
After restart works 1-2 houers than the same.

Log:

```
INFO   | jvm 1    | 2016/05/25 08:56:45 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2016/05/25 08:56:45 | javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of org.traccar.web.shared.model.Device.iconRotation
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:458)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.traccar.web.server.model.MovementDetector.getDevices(MovementDetector.java:118)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.traccar.web.server.model.MovementDetector.doWork(MovementDetector.java:71)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 | Caused by: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of org.traccar.web.shared.model.Device.iconRotation
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:126)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:713)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:362)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:4718)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:188)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1115)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.processResultSet(Loader.java:973)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.doQuery(Loader.java:921)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.doList(Loader.java:2554)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.doList(Loader.java:2540)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.Loader.list(Loader.java:2365)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1264)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:449)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   ... 10 more
INFO   | jvm 1    | 2016/05/25 08:56:45 | Caused by: java.lang.IllegalArgumentException: Can not set boolean field org.traccar.web.shared.model.Device.iconRotation to null value
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at java.lang.reflect.Field.set(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:122)
INFO   | jvm 1    | 2016/05/25 08:56:45 |   ... 30 more
INFO   | jvm 1    | 2016/05/25 08:56:45 | 
INFO   | jvm 1    | 2016/05/25 08:56:57 | [qtp181655338-646] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/05/25 08:56:57 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositions()' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of org.traccar.web.shared.model.Device.iconRotation
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 | Caused by: javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of org.traccar.web.shared.model.Device.iconRotation
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:458)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.traccar.web.server.model.DataServiceImpl.getDevices(DataServiceImpl.java:394)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.traccar.web.server.model.DataServiceImpl.getLatestPositions(DataServiceImpl.java:781)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   ... 42 more
INFO   | jvm 1    | 2016/05/25 08:56:57 | Caused by: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of org.traccar.web.shared.model.Device.iconRotation
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:126)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:713)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:362)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:4718)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:188)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1115)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.processResultSet(Loader.java:973)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.doQuery(Loader.java:921)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.doList(Loader.java:2554)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.doList(Loader.java:2540)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.Loader.list(Loader.java:2365)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1264)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:449)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   ... 50 more
INFO   | jvm 1    | 2016/05/25 08:56:57 | Caused by: java.lang.IllegalArgumentException: Can not set boolean field org.traccar.web.shared.model.Device.iconRotation to null value
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at java.lang.reflect.Field.set(Unknown Source)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:122)
INFO   | jvm 1    | 2016/05/25 08:56:57 |   ... 70 more
```

Config:

```
    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>C:\Program Files (x86)\Traccar\web</entry>
    <entry key='web.type'>old</entry>
    <entry key='web.application'>C:\Program Files (x86)\Traccar\web\traccar-web.war</entry>  

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>C:\Program Files (x86)\Traccar\logs\tracker-server.log</entry>

    <!-- DATABASE CONFIG -->

<!-- 
    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:/opt/traccar/data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>
-->

<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://localhost:3306/XXXXXXXXXXX?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>xxxxxxxxx</entry> 
<entry key='database.password'>xxxxxxxxxxx</entry>

    <entry key='database.checkTable'>xxxxxxxxxxxxxxxx</entry>

    <entry key='database.selectSchemaVersion'>
        SELECT * FROM xxxxxxxxxxxxxx;
    </entry>

    <entry key='database.createSchema'>
        CREATE TABLE "user" (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        email VARCHAR(128) NOT NULL UNIQUE,
        hashedPassword VARCHAR(128) NOT NULL,
        salt VARCHAR(128) DEFAULT '' NOT NULL,
        readonly BIT DEFAULT 0 NOT NULL,
        admin BIT DEFAULT 0 NOT NULL,
        map VARCHAR(128),
        language VARCHAR(128),
        distanceUnit VARCHAR(128),
        speedUnit VARCHAR(128),
        latitude DOUBLE PRECISION DEFAULT 0 NOT NULL,
        longitude DOUBLE PRECISION DEFAULT 0 NOT NULL,
        zoom INT DEFAULT 0 NOT NULL);

        CREATE TABLE device (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        uniqueId VARCHAR(128) NOT NULL UNIQUE,
        status VARCHAR(128),
        lastUpdate TIMESTAMP,
        positionId INT);

        CREATE TABLE user_device (
        userId INT NOT NULL,
        deviceId INT NOT NULL,
        "read" BIT DEFAULT 1 NOT NULL,
        "write" BIT DEFAULT 1 NOT NULL,
        FOREIGN KEY (userId) REFERENCES "user" (id) ON DELETE CASCADE,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);

        CREATE INDEX user_device_userId ON user_device(userId);

        CREATE TABLE position (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(128),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        fixTime TIMESTAMP NOT NULL,
        valid BIT NOT NULL,
        latitude DOUBLE PRECISION NOT NULL,
        longitude DOUBLE PRECISION NOT NULL,
        altitude FLOAT NOT NULL,
        speed FLOAT NOT NULL,
        course FLOAT NOT NULL,
        address VARCHAR(512),
        attributes VARCHAR(4096) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);

        CREATE INDEX position_deviceId_fixTime ON position (deviceId, fixTime);

        CREATE TABLE server (
        id INT PRIMARY KEY AUTO_INCREMENT,
        registration BIT NOT NULL,
        map VARCHAR(128),
        bingKey VARCHAR(128),
        mapUrl VARCHAR(128),
        language VARCHAR(128),
        distanceUnit VARCHAR(128),
        speedUnit VARCHAR(128),
        latitude DOUBLE PRECISION DEFAULT 0 NOT NULL,
        longitude DOUBLE PRECISION DEFAULT 0 NOT NULL,
        zoom INT DEFAULT 0 NOT NULL);

        CREATE TABLE traccar (
        version INT DEFAULT 0 NOT NULL);

        INSERT INTO traccar (version) VALUES (302);
    </entry>

    <entry key='database.selectServers'>
        SELECT * FROM server;
    </entry>

    <entry key='database.insertServer'>
        INSERT INTO server (registration, latitude, longitude, zoom)
        VALUES (:registration, :latitude, :longitude, :zoom);
    </entry>

    <entry key='database.updateServer'>
        UPDATE server SET
        registration = :registration,
        map = :map,
        bingKey = :bingKey,
        mapUrl = :mapUrl,
        language = :language,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom
        WHERE id = :id;
    </entry>

    <entry key='database.loginUser'>
        SELECT * FROM "user"
        WHERE email = :email;
    </entry>

    <entry key='database.selectUser'>
        SELECT * FROM "user"
        WHERE id = :id;
    </entry>

<entry key='database.selectUsersAll'>
    SELECT id, login AS name, email, readOnly AS readonly, admin FROM users;
</entry>

    <entry key='database.insertUser'>
        INSERT INTO "user" (name, email, hashedPassword, salt, admin)
        VALUES (:name, :email, :hashedPassword, :salt, :admin);
    </entry>

    <entry key='database.updateUser'>
        UPDATE "user" SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        language = :language,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom
        WHERE id = :id;
    </entry>

    <entry key='database.updateUserPassword'>
        UPDATE "user" SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
    </entry>

    <entry key='database.deleteUser'>
        DELETE FROM "user" WHERE id = :id;
    </entry>

<entry key='database.selectDevicePermissions'>
    SELECT u.id AS userId, d.id AS deviceId FROM users u, devices d WHERE u.admin=1
    UNION
    SELECT ud.users_id AS userId, ud.devices_id AS deviceId FROM users_devices ud
    INNER JOIN users u ON ud.users_id=u.id
    WHERE u.admin=0 AND u.readOnly=0
</entry>

<entry key='database.selectDevicesAll'>
    SELECT * FROM devices;
</entry>

    <entry key='database.selectDevices'>
        SELECT * FROM device d INNER JOIN user_device ud ON d.id = ud.deviceId WHERE ud.userId = :userId;
    </entry>

    <entry key='database.insertDevice'>
        INSERT INTO device (name, uniqueId) VALUES (:name, :uniqueId);
    </entry>

    <entry key='database.updateDevice'>
        UPDATE device SET name = :name, uniqueId = :uniqueId WHERE id = :id;
    </entry>

    <entry key='database.deleteDevice'>
        DELETE FROM device WHERE id = :id;
    </entry>

<!-- entry key='database.linkDevice'>
    INSERT INTO user_device (userId, deviceId) VALUES (:userId, :deviceId);
</entry -->

    <entry key='database.unlinkDevice'>
        DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM position WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime;
    </entry>

<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :protocol, :now, :deviceTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
</entry>

<entry key='database.selectLatestPositions'>
    SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime, 
    valid, latitude, longitude, altitude, speed, course, address, other AS attributes 
    FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
</entry>

<entry key='database.updateLatestPosition'>
    UPDATE devices SET latestPosition_id = :id WHERE id = :deviceId;
</entry>
```

I hope you can help.

Thx

**Comment by vitalidze** [comment]
Looks like this issue is related to the [Traccar Web UI Mod](https://github.com/vitalidze/traccar-web) project. There is some issue with the data in `devices` table. How do you add rows there? I think you are inserting rows directly to the database and in column `iconRotation` there is a `NULL` value for such devices.

**Comment by ReabRed** [comment]
Device ID 25 'iconRotation' = NULL
i change to b'1' and works.
Thank you very much
