### ISSUE TITLE
WARNING : traccar may have failed to start, (Illegal Seek)

### ISSUE THREAD

**Issue by FanerK** [traccar/traccar#2054]
Hi,

I Have Problem, My traccar don't running. How to solving?

```
[root@Track ~] # /opt/traccar/bin/traccar restart
Stopping traccar...
traccar was not running.
Starting traccar...
Waiting for traccar...
WARNING: traccar may have failed to start
```

and i trying

```
[root@Track ~] # /opt/traccar/bin/traccar console
wrapper   | 4402 pid file, /opt/traccar/bin/./traccar.pid, already exist
wrapper   | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: illegal seek
```

who's can help me caused i don't know what i can doing again ?

**Comment by tananaev** [comment]
Check wrapper log file for more details about the error.

**Comment by FanerK** [comment]
This is wrapper log file error
2016-06-27 08:28:16  INFO: Shutting down server...
2016-06-27 08:28:16  INFO: Closing connection by disconnect
2016-06-27 08:28:16  INFO: Closing connection by disconnect
2016-06-27 08:28:18  INFO: Starting server...
2016-06-27 08:28:18  INFO: Operating System name: Linux version: 2.6.32-573.3.1.el6.x86_64 architecture: amd64
2016-06-27 08:28:18  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2016-06-27 08:28:18  INFO: Memory Limit heap: 1742mb non-heap: 214mb
2016-06-27 08:28:18  INFO: Version: 2.12-SNAPSHOT

**Comment by tananaev** [comment]
No, it's not.

**Comment by FanerK** [comment]
how to check the wrapper log file?  
I do not understand

**Comment by tananaev** [comment]
Find the file and open it in any text viewer.

**Comment by FanerK** [comment]
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  | 
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperSimpleApp: 
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 393; columnNumber: 14; The content of element type "properties" must match "(comment?,entry*)".
jvm 1    | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:76)
jvm 1    | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Properties.java:868)
jvm 1    | WrapperSimpleApp Error: 	at org.traccar.ServerManager.init(ServerManager.java:91)
jvm 1    | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:27)
jvm 1    | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
jvm 1    | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
jvm 1    | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
jvm 1    | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 393; columnNumber: 14; The content of element type "properties" must match "(comment?,entry*)".
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTDValidator.java:1994)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(XMLDTDValidator.java:879)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
jvm 1    | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
jvm 1    | WrapperSimpleApp Error: 	at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
jvm 1    | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:74)
jvm 1    | WrapperSimpleApp Error: 	... 9 more
wrapper  | <-- Wrapper Stopped
[root@Track ~]#

**Comment by tananaev** [comment]
There is some problem with your config file.

**Comment by FanerK** [comment]
How to solve your problem it?

**Comment by tananaev** [comment]
Check your config file and find the issue there. It must be some of your modifications.

**Comment by FanerK** [comment]
Oke,
next problem this;
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)
2016-06-27 11:34:38  WARN: maps.googleapis.com - java.net.UnknownHostException (AbstractPlainSocketImpl.java:178)

**Comment by tananaev** [comment]
Looks like you don't have internet connection. DNS lookup fails.

**Comment by FanerK** [comment]
I've tried to google and successful ping

**Comment by tananaev** [comment]
Can I see ping output?

**Comment by FanerK** [comment]
[root@Track ~]# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=53 time=24.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=53 time=24.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=53 time=24.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=53 time=29.7 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=53 time=23.8 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=53 time=24.2 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=53 time=24.3 ms
^C
--- 8.8.8.8 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6506ms
rtt min/avg/max/mdev = 23.806/24.964/29.740/1.957 ms

**Comment by tananaev** [comment]
Not sure why you are pinging IP address if the problem is with DNS. Please try following:
```
ping maps.googleapis.com
```

**Comment by FanerK** [comment]
I have tried
[root@Track ~]# ping maps.googleapis.com
ping : unknown host maps.googleapis.com

**Comment by tananaev** [comment]
Well, it means DNS doesn't work on your server. It has nothing to do with Traccar.
