### ISSUE TITLE
posgres error urgent

### ISSUE THREAD

**Issue by warlockopy** [traccar/traccar#2089]
Can you help me with this error

```
Secure Shell Terminal: vt220
jvm 1    | WrapperSimpleApp Error: org.postgresql.util.PSQLException: ERROR: syntax error at or near "AUTO_IN
CREMENT"                                                                                                     
jvm 1    | WrapperSimpleApp Error:   Position: 50                                                            
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(Quer
yExecutorImpl.java:2270)                                                                                     
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecu
torImpl.java:1998)                                                                                           
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl
.java:255)                                                                                                   
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2S
tatement.java:570)                                                                                           
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(Abstr
actJdbc2Statement.java:420)                                                                                  
jvm 1    | WrapperSimpleApp Error:      at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(Abstract
Jdbc2Statement.java:366)                                                                                     
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(N
ewProxyPreparedStatement.java:410)                                                                           
jvm 1    | WrapperSimpleApp Error:      at org.traccar.database.QueryBuilder.executeUpdate(QueryBuilder.java:
412)                                                                                                         
jvm 1    | WrapperSimpleApp Error:      at org.traccar.database.DataManager.initDatabaseSchema(DataManager.ja
va:181)                                                                                                      
jvm 1    | WrapperSimpleApp Error:      at org.traccar.database.DataManager.<init>(DataManager.java:64)      
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Context.init(Context.java:98)                         
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Main.main(Main.java:26)                               
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)       
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorIm
pl.java:62)                                                                                                  
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAc
cessorImpl.java:43)                                                                                          
jvm 1    | WrapperSimpleApp Error:      at java.lang.reflect.Method.invoke(Method.java:498)                  
jvm 1    | WrapperSimpleApp Error:      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.j
ava:325)                                                                                                     
jvm 1    | WrapperSimpleApp Error:      at java.lang.Thread.run(Thread.java:745)                             
wrapper  | <-- Wrapper Stopped 
```

here the config

```
   <!-- DATABASE CONFIG -->                                                                                 

   <entry key='database.driver'>org.postgresql.Driver</entry>                                                
   <entry key='database.url'>jdbc:postgresql://127.0.0.1:5432/traccar</entry>                                
   <entry key='database.user'>traccardb</entry>                                                              
   <entry key='database.password'>sutraccar2016</entry> 
```

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by warlockopy** [comment]
3.2

**Comment by tananaev** [comment]
Please install latest version.
