### ISSUE TITLE
wrapper file log Problem

### ISSUE THREAD

**Issue by fcazar** [traccar/traccar#2120]
@tananaev  Hi Friend, Your help please, I have a big problem, I have a traccar site on ubuntu server, It work fine for 1 month, but the last 2 sundays, the wrapper log  Increase the size, the last week was 100 Gb, and today the file is in 3.5 GB, Also when this occur this traccar stop working,
For fix the problem,  In both saurdays I delete this file an restart the server, 

In both weeks its begin at 8:00 local hour 9:00 server hour

Please your help

the last lines at the file are: 

```
INFO   | jvm 1    | 2016/07/17 11:08:58 | Jul 17, 2016 11:08:58 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/07/17 11:08:58 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/07/17 11:08:58 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/07/17 11:08:58 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/07/17 11:08:58 |
INFO   | jvm 1    | 2016/07/17 11:08:59 | Jul 17, 2016 11:08:59 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/07/17 11:08:59 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/07/17 11:08:59 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/07/17 11:08:59 |       at java.lang.Thread.run(Thread.java:745)
```

**Comment by tananaev** [comment]
You have too many open connections. This problem has been discussed on forum and GitHub multiple times. The solution is to increase connection limit (it's OS limit, not Traccar), and configure `resetDelay` parameter.

**Comment by fcazar** [comment]
do yo have the link, I don´t find the forum

**Comment by tananaev** [comment]
Here are a couple of examples:

https://www.traccar.org/forums/topic/anyway-to-find-server-service-not-running-3-1/
https://github.com/tananaev/traccar/issues/1524

There are many more threads.
