### ISSUE TITLE
It does not run v3.6

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#2212]
Hi. First of all. thanks for your help so valuable.
tables and records were created.

When you run, it does not detect error.
When you open the browser does not load the page.
observe the status
and not running traccar

How can I solve that?

MY TERMINAL:

```
eduardo@EvG30:/opt/traccar/bin$
sudo /opt/traccar/bin/traccar start
Starting traccar...
Waiting for traccar......
running: PID:8583
eduardo@EvG30:/opt/traccar/bin$ sudo /opt/traccar/bin/traccar status
traccar is running: PID:8583, Wrapper:STARTED, Java:STARTED
eduardo@EvG30:/opt/traccar/bin$ sudo /opt/traccar/bin/traccar status
traccar is running: PID:8583, Wrapper:STARTED, Java:STARTED
eduardo@EvG30:/opt/traccar/bin$ sudo /opt/traccar/bin/traccar status
traccar is not running.
eduardo@EvG30:/opt/traccar/bin$ nano /opt/traccar/logs/wrapper.log.20160813
```

MY WRAPPER:

```
INFO | jvm 1 | 2016/08/13 07:02:14 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @44128ms
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp:
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: Encountered an error running main:
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: java.lang.NoClassDefFoundError: javax/annotation/Priority
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:483)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag.access$100(ComponentBag.java:89)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag$5.call(ComponentBag.java:408)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag$5.call(ComponentBag.java:398)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:398)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:235)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:420)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:425)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.traccar.web.WebServer.initApi(WebServer.java:150)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.traccar.web.WebServer.(WebServer.java:92)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.traccar.Context.init(Context.java:196)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.traccar.Main.main(Main.java:30)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
INFO | jvm 1 | 2016/08/13 07:02:14 | WrapperSimpleApp Error: ... 21 more
STATUS | wrapper | 2016/08/13 07:02:16 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Looks like some class is missing. Are you sure you are using original version? Also, what version of Java do you have installed?

**Comment by evigra** [comment]
It is the original version, download Yesterday
Linux 64 bit	traccar-linux-64-3.6.zip	09-Jul-2016

> eduardo@EvG30:~/web/sistema$  java -version
> openjdk version "9-internal"
> OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
> OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by tananaev** [comment]
I think you need to reinstall Java. I don't even know what 9-interval version means. Install stable version 7 or 8.
