### ISSUE TITLE
WebSocket java client

### ISSUE THREAD

**Issue by rarora13** [traccar/traccar#2289]
Hi, 

I have written simple code for creating java client to connect to web socket using the url as follows:
"ws://localhost:8082/api/socket".  But that is not connecting to the web socket.

Please share with me a sample java code to connect to the server's web socket.

I wanted to feed the Positions data to another system.

Regards
Rakesh Arora

**Comment by tananaev** [comment]
You can find Java example here in Traccar Manager [MainFragment](https://github.com/tananaev/traccar-manager-android/blob/master/app/src/main/java/org/traccar/manager/MainFragment.java#L240).

**Comment by marko89kv** [comment]
@rarora13 make sure you have the session token attached when connecting to WS

**Comment by rarora13** [comment]
Hi All,
I am glad to get the quick response.
But I am not able to connect as a client from my java code.

Following is the error I am getting:
java.net.ConnectException: Failed to connect to /122.176.42.190:8082
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Following is the source code I have written:


import java.io.IOException;

import okio.Buffer;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import okhttp3.ws.WebSocket;
import okhttp3.ws.WebSocketCall;
import okhttp3.ws.WebSocketListener;

/**
 * @author Rakesh
 *
 */
public class MyWebsocket {

	public static void main(String[] args) {
		Request request = new Request.Builder().url("ws://122.176.42.190:8082/api/socket").build();
		final OkHttpClient client = new OkHttpClient();
		String credentials = "rarora13@gmail.com" + ":" + "<mypassword>";
        // create Base64 encodet string
        final String basic =
                "Basic " + com.sun.jersey.core.util.Base64.encode(credentials.getBytes());
		request.header("Authorization: "+ basic);
		
		WebSocketCall webSocket = WebSocketCall.create(client, request);
		
        webSocket.enqueue(new WebSocketListener() {

			public void onClose(int arg0, String arg1) {
				System.out.println("closed");
			}

			public void onFailure(IOException arg0, Response arg1) {
				if(arg1 != null)
					System.out.println("failed to connect:"+arg1.message());
				arg0.printStackTrace();
				
			}

			public void onMessage(ResponseBody arg0) throws IOException {
				System.out.println("message received");
			}

			public void onOpen(WebSocket arg0, Response arg1) {
				System.out.println("opened the connect");
			}

			public void onPong(Buffer arg0) {
				System.out.println("ponged");
			}
        });
	}
	
}

**Comment by tananaev** [comment]
Try to use session cookie instead of HTTP authorization header.

**Comment by rarora13** [comment]
No luck, I am still getting exactly same error:

```
failed to connect:Endpoint Creation Failed
java.net.ProtocolException: Expected HTTP 101 response but was '503 Endpoint Creation Failed'
	at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:122)
	at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Following is the changes in code:

```
Request request = new Request.Builder().url("ws://122.176.42.190:8082/api/socket").build();
		
		String credentials = "rarora13@gmail.com" + ":" + "...";
        // create Base64 encodet string
        final String basic =
                "Basic " + com.sun.jersey.core.util.Base64.encode(credentials.getBytes());
		//request.header("Authorization: "+ basic);
		
		 final OkHttpClient client = new OkHttpClient().newBuilder().addInterceptor(new Interceptor() {
			
			public Response intercept(Chain chain) throws IOException {
                final Request original = chain.request();

                final Request authorized = original.newBuilder()
                        .addHeader("Authorization", basic)
                        .build();

                return chain.proceed(authorized);
            }
		}).build();
		
		WebSocketCall webSocket = WebSocketCall.create(client, request);
		
        webSocket.enqueue(new WebSocketListener() {.................});
```

Please suggest.

**Comment by tananaev** [comment]
But where is the code to create a session?

**Comment by rarora13** [comment]
Hi, 

Please share some sample code about how should I create a session.

This is not an android environment, but java code running on any other server.

Regards
Rakesh Arora

**Comment by tananaev** [comment]
I already shared a sample. I don't have any other.

**Comment by SiddiqueAhmad** [comment]
the link is showing 404 which you shared for sample, i am getting same error but connecting via nodejs and using basic http auth, 
what you suggest for this

**Comment by tananaev** [comment]
Here is an updated link: [MainFragment.java#L240](https://github.com/tananaev/traccar-manager-android/blob/native/app/src/main/java/org/traccar/manager/MainFragment.java#L240).

**Comment by SiddiqueAhmad** [comment]
thanks for quick reply, i need to set cookies for making it work ?

**Comment by tananaev** [comment]
Yes, you need cookie for authentication.

**Comment by exaucae** [comment]
FYI: I've just lauched A java (springboot) websocket client for traccar that handles cookie retrieval and all the stuff internally: https://github.com/exaucae/traccar-websocket-client 

Feedback appreciated.
