### ISSUE TITLE
Update V3.6 to 3.7

### ISSUE THREAD

**Issue by kokarat** [traccar/traccar#2358]
I got this error when try to update V3.6 to 3.7

```
Can't create table 'gps_upbox_v3.#sql-3c3_265' (errno: 150) [Failed SQL: ALTER TABLE gps_upbox_v3.devices # **ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]** jvm 1 | WrapperSimpleApp Error: at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605) jvm 1 
```

```
root@Atgroup:~# sudo /opt/traccar/bin/traccar console
Running traccar...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.28
wrapper  |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Clearing database change log checksums
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Successfully acquired change log lock
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Successfully released change log lock
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Successfully acquired change log lock
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Reading from gps_upbox_v3.DATABASECHANGELOG
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: Reading from gps_upbox_v3.DATABASECHANGELOG
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Data updated in devices
jvm 1    | SEVERE 9/22/16 1:26 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Change Set changelog-3.7::changelog-3.7::author failed.  Error: Can't create table 'gps_upbox_v3.#sql-3c3_265' (errno: 150) [Failed SQL: ALTER TABLE gps_upbox_v3.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
jvm 1    | INFO 9/22/16 1:26 AM: liquibase: changelog-3.7::changelog-3.7::author: Successfully released change log lock
jvm 1    | WrapperSimpleApp:
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-3.7::changelog-3.7::author:
jvm 1    | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: Can't create table 'gps_upbox_v3.#sql-3c3_265' (errno: 150) [Failed SQL: ALTER TABLE gps_upbox_v3.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
jvm 1    | WrapperSimpleApp Error:  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605)
jvm 1    | WrapperSimpleApp Error:  at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
jvm 1    | WrapperSimpleApp Error:  at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
jvm 1    | WrapperSimpleApp Error:  at liquibase.Liquibase.update(Liquibase.java:214)
jvm 1    | WrapperSimpleApp Error:  at liquibase.Liquibase.update(Liquibase.java:192)
jvm 1    | WrapperSimpleApp Error:  at liquibase.Liquibase.update(Liquibase.java:188)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:141)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.database.DataManager.<init>(DataManager.java:67)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.Context.init(Context.java:150)
jvm 1    | WrapperSimpleApp Error:  at org.traccar.Main.main(Main.java:35)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
jvm 1    | WrapperSimpleApp Error:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | WrapperSimpleApp Error:  at java.lang.reflect.Method.invoke(Method.java:606)
jvm 1    | WrapperSimpleApp Error:  at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error:  at java.lang.Thread.run(Thread.java:745)
jvm 1    | WrapperSimpleApp Error: Caused by: liquibase.exception.DatabaseException: Can't create table 'gps_upbox_v3.#sql-3c3_265' (errno: 150) [Failed SQL: ALTER TABLE gps_upbox_v3.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
jvm 1    | WrapperSimpleApp Error:  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
jvm 1    | WrapperSimpleApp Error:  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
jvm 1    | WrapperSimpleApp Error:  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273)
jvm 1    | WrapperSimpleApp Error:  at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255)
jvm 1    | WrapperSimpleApp Error:  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:568)
jvm 1    | WrapperSimpleApp Error:  ... 15 more
jvm 1    | WrapperSimpleApp Error: Caused by: java.sql.SQLException: Can't create table 'gps_upbox_v3.#sql-3c3_265' (errno: 150)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
jvm 1    | WrapperSimpleApp Error:  at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
jvm 1    | WrapperSimpleApp Error:  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
jvm 1    | WrapperSimpleApp Error:  ... 20 more
wrapper  | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Looks similar to #2342. Please check if that solution helps you.

**Comment by Abyss777** [comment]
I think it is another problem.
It can't create fk from `devices.groupid` to `groups.id`. But cleanup looks had worked.

@kokarat what DB do you use?

**Comment by kokarat** [comment]
@Abyss777  Mysql 5.5.52

**Comment by Abyss777** [comment]
Very strange... it works on 5.5.50 for me
Did you do some manual changes with db schema?
Could you give an access to that DB via phpmyadmin or something?

**Comment by Abyss777** [comment]
Did you allow NULL for `groups`.`id` ?

**Comment by kokarat** [comment]
<img width="913" alt="screenshot 2016-09-22 13 01 06" src="https://cloud.githubusercontent.com/assets/147563/18738296/b03cb90e-80c4-11e6-81aa-452979282e21.png">

**Comment by tananaev** [comment]
What if you manually execute the query:
```
ALTER TABLE gps_upbox_v3.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL;
```

**Comment by kokarat** [comment]
@tananaev 
> ALTER TABLE gps_upbox_v3.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES gps_upbox_v3.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL;


I got this error 
> Can't create table 'gps_upbox_v3.#sql-3c3_6c1' (errno: 150)

**Comment by tananaev** [comment]
Check this comment and make sure all conditions are correct:

http://stackoverflow.com/a/4673775/2548565
