### ISSUE TITLE
mysql database issue.

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2362]
Hi Tananaev,

To make mysql running I have done the following:

1 . Created a mysql database and a user for this database
2.  Granted All priviliges on the database.name.*

Opened traccar.xml and added following:

```
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://localhost:3306/databasename?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8</entry>
    <entry key='database.user'>userxxx</entry> 
    <entry key='database.password'>xxxxxxxxxx</entry>
```

however, cant get it to 

work, attached please see the wrapper log from server. It is complaing about some type of permission:

```
STATUS | wrapper  | 2016/09/23 02:52:37 | TERM trapped.  Shutting down.
INFO   | jvm 1    | 2016/09/23 02:52:37 | [Thread-13] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@354ddfc5{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/09/23 02:52:37 | [Thread-13] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@482c4313{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/09/23 02:52:38 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/09/23 02:52:45 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/23 02:52:45 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/23 02:52:45 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/23 02:52:45 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/23 02:52:45 | 
STATUS | wrapper  | 2016/09/23 02:52:45 | Launching a JVM...
INFO   | jvm 1    | 2016/09/23 02:52:47 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/23 02:52:52 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/09/23 02:52:54 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @7785ms
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:272)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:98)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:79)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:218)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/23 02:52:55 | WrapperSimpleApp Error:   at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2016/09/23 02:52:57 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/09/23 02:57:43 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/23 02:57:43 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/23 02:57:43 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/23 02:57:43 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/23 02:57:43 | 
STATUS | wrapper  | 2016/09/23 02:57:44 | Launching a JVM...
INFO   | jvm 1    | 2016/09/23 02:57:44 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/23 02:57:45 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/09/23 02:57:46 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @2061ms
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:272)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:98)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:79)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:218)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/23 02:57:46 | WrapperSimpleApp Error:   at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2016/09/23 02:57:48 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Are you sure that you are using latest official release without any modifications?

**Comment by akmal1999** [comment]
I am using the .7 that is the latest.

**Comment by tananaev** [comment]
Do you mean 3.7? No modifications? Clean installation, right?

**Comment by akmal1999** [comment]
i tried to put the wrapper together from the demo to the opt traccar it did not work. that wrapper-web is in there but doesnt do anything. i did no other modification than mysql.

**Comment by tananaev** [comment]
I'm completely confused now. What wrapper from demo? What's wrapper-web?

**Comment by akmal1999** [comment]
I have not brought any changes to make it clear. It is a clean install and i only changed the traccar.xml which I pasted.

**Comment by tananaev** [comment]
Can I have access to the server to take a look?

**Comment by akmal1999** [comment]
so finally I got it figured.. the database is connected but, no tables got created and the website does not work either because it does not see the tables in the database.

**Comment by akmal1999** [comment]
here is the log i am getting.:

 Operating system name: Linux version: 2.6.32-642.3.1.el6.x86_64 architecture: amd64
2016-09-23 21:54:52  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.111-b01
2016-09-23 21:54:52  INFO: Memory limit heap: 592mb non-heap: 214mb
2016-09-23 21:54:52  INFO: Character encoding: UTF-8 charset: UTF-8
2016-09-23 21:54:52  INFO: Version: 3.7-SNAPSHOT
2016-09-23 21:54:55  WARN: Table 'acegpsone.groups' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:245 < DeviceManager:243 < ...)
2016-09-23 21:54:56  WARN: Table 'acegpsone.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:318 < PermissionsManager:85 < ...)
"tracker-server.log" 15049L, 4589123C

**Comment by tananaev** [comment]
Do you have "database.changelog" parameter in your config?
