### ISSUE TITLE
TRACCAR Stop

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#2363]
My traccar is original version
Help me please

In my terminal

```
[root@v217599 evigra]# /opt/traccar/bin/traccar status
traccar is not running.
[root@v217599 evigra]# /opt/traccar/bin/traccar start
Starting traccar...
Waiting for traccar......
running: PID:1969
[root@v217599 evigra]# /opt/traccar/bin/traccar status
traccar is running: PID:1969, Wrapper:STARTED, Java:STARTED
[root@v217599 evigra]# /opt/traccar/bin/traccar status
traccar is running: PID:1969, Wrapper:STARTED, Java:STOPPING
[root@v217599 evigra]# /opt/traccar/bin/traccar status
traccar is not running.
```

In my log

```
2016-09-23 16:26:37  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:37  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:37  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:37  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:41  WARN: InvocationTargetException (... < QueryBuilder:336 < *:413 < DataManager:565 < GeofenceManager:115 < ...)
2016-09-23 16:26:41  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:41  WARN: InvocationTargetException (... < QueryBuilder:336 < *:413 < DataManager:565 < GeofenceManager:115 < ...)
2016-09-23 16:26:41  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
2016-09-23 16:26:41  WARN: InvocationTargetException (... < QueryBuilder:336 < *:413 < DataManager:565 < GeofenceManager:115 < ...)
```

In my wrapper

```
STATUS | wrapper  | 2016/09/23 11:26:32 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/23 11:26:32 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/23 11:26:32 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/23 11:26:32 |
STATUS | wrapper  | 2016/09/23 11:26:32 | Launching a JVM...
INFO   | jvm 1    | 2016/09/23 11:26:32 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/23 11:26:33 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/09/23 11:26:34 | INFO 9/23/16 4:26 PM: liquibase: Clearing database change log checksums
INFO   | jvm 1    | 2016/09/23 11:26:34 | INFO 9/23/16 4:26 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/09/23 11:26:34 | INFO 9/23/16 4:26 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/09/23 11:26:34 | INFO 9/23/16 4:26 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/09/23 11:26:36 | INFO 9/23/16 4:26 PM: liquibase: Reading from admin_traccar36.DATABASECHANGELOG
INFO   | jvm 1    | 2016/09/23 11:26:36 | INFO 9/23/16 4:26 PM: liquibase: Reading from admin_traccar36.DATABASECHANGELOG
INFO   | jvm 1    | 2016/09/23 11:26:36 | INFO 9/23/16 4:26 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/09/23 11:26:36 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @4161ms
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp:
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp Error:   at org.traccar.database.GeofenceManager.refresh(GeofenceManager.java:156)
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp Error:   at org.traccar.database.GeofenceManager.<init(GeofenceManager.java:56)
INFO   | jvm 1    | 2016/09/23 11:26:41 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:204)
```

**Comment by jaimzj** [comment]
Hi, Not sure if  my answer would be relevant,.

In my case the reason was. I upgraded from 3.6 to 3.7, I believe you might have also done the same? that is a upgrade.

You might have removed traccar from init, but not run the second step.
Remove traccar directory (sudo rm -R /opt/traccar)

Remove the traccar directory and then install 3.7 and try.

**Comment by tananaev** [comment]
It doesn't looks like you are using official version 3.7.
