### ISSUE TITLE
Traccar Server Cann't Start  for version 3.7 in Windows 7.

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar#2459]
As per instruction in http://traccar.litvak.su/installation.html. Untill 7. comment run successyfully.But After that when i wants to start traccar server ,error message shown "windows could not start traccar on Local computer" And Cannot create any table in database(mysql).
please guide me what i needs to solve this problem?

wrapper.log file errors are

```
STATUS | wrapper  | 2016/10/19 12:34:37 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/10/19 12:34:37 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/19 12:34:37 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/19 12:34:37 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/19 12:34:37 | 
STATUS | wrapper  | 2016/10/19 12:34:37 | Launching a JVM...
INFO   | jvm 1    | 2016/10/19 12:34:38 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/19 12:34:38 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/19 12:34:39 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @1266ms
INFO   | jvm 1    | 2016/10/19 12:34:40 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO   | jvm 1    | 2016/10/19 12:34:40 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@18b57d75{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/10/19 12:34:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2016/10/19 12:34:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@7ee4b2fa{/,file:/C:/Program%20Files%20(x86)/Traccar/web/,AVAILABLE}{C:\Program Files (x86)\Traccar\web}
INFO   | jvm 1    | 2016/10/19 12:34:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@555fff37{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/19 12:34:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @3099ms
INFO   | jvm 1    | 2016/10/19 12:35:48 | [Thread-11] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@555fff37{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/10/19 12:35:48 | [Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@7ee4b2fa{/,file:/C:/Program%20Files%20(x86)/Traccar/web/,UNAVAILABLE}{C:\Program Files (x86)\Traccar\web}
INFO   | jvm 1    | 2016/10/19 12:35:48 | [Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@18b57d75{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/10/19 12:35:49 | <-- Wrapper Stopped
STATUS | wrapper  | 2016/10/19 12:36:14 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/10/19 12:36:14 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/19 12:36:14 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/19 12:36:14 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/19 12:36:14 | 
STATUS | wrapper  | 2016/10/19 12:36:14 | Launching a JVM...
INFO   | jvm 1    | 2016/10/19 12:36:14 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/19 12:36:15 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/19 12:36:15 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @1180ms
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.traccar.database.DeviceManager.getAllGroups(DeviceManager.java:272)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:98)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:79)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:218)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/19 12:36:16 | WrapperSimpleApp Error:   at java.lang.Thread.run(Unknown Source)
STATUS | wrapper  | 2016/10/19 12:36:18 | <-- Wrapper Stopped
```

And traccar-server.log reports are

```
2016-10-19 12:27:39  INFO: Shutting down server...
2016-10-19 12:27:41  INFO: Operating system name: Windows 7 version: 6.1 architecture: amd64
2016-10-19 12:27:41  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.73-b02
2016-10-19 12:27:41  INFO: Memory limit heap: 889mb non-heap: 0mb
2016-10-19 12:27:41  INFO: Character encoding: UTF-8 charset: UTF-8
2016-10-19 12:27:41  INFO: Version: 3.7-SNAPSHOT
2016-10-19 12:27:42  WARN: Table 'traccar.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:318 < PermissionsManager:85 < ...)
2016-10-19 12:27:42  WARN: Table 'traccar.user_group' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:197 < PermissionsManager:100 < ...)
2016-10-19 12:27:42  INFO: Starting server...
```

**Comment by tananaev** [comment]
Traccar Web UI mod from Litvak is not an official Traccar project. Please contact the author for support.
