### ISSUE TITLE
Traccar & OpenGTS integration

### ISSUE THREAD

**Issue by agusu888** [traccar/traccar#2517]
Dear Tananaev,

I have made configuration for Traccar-OpenGTS integration, but didn't received any data on GTS mysql database. Following are configuration on traccar.xml :
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>
<properties>
    <!-- SERVER CONFIG -->
    <entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>
    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <!-- DATABASE CONFIG -->
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/gts?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessio$
    <entry key='database.user'>root</entry>
    <entry key='database.password'>Ap88G3J8CCCzOEqE</entry>

   <!-->
        id - Integer
        imeiNumber - String
    <-->

    <entry key='database.selectDevicesAll'>
        SELECT CONCAT('1', imeiNumber) AS id, imeiNumber AS uniqueId FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
    </entry>
<!—>
<!-->
        device_id - Integer
        time - Date
        valid - Boolean
        latitude - Double
        longitude - Double
        speed - Double
        course - Double
    <-->

    <entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:fixTime), lastUpdateTime = UNIX_TIME$
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :addres$
        COMMIT;
    </entry>

    <!-- PROTOCOL CONFIG -->
    <entry key='easytrack.enable'>true</entry>
    <entry key='easytrack.port'>5056</entry>
</properties>
```
Need your kind help with many thanks,
Agus Utomo, Indonesia

**Comment by tananaev** [comment]
You should check server logs to see what's happening. Check this:

https://www.traccar.org/troubleshooting

**Comment by agusu888** [comment]
here is some records in log file:
2016-11-09 12:25:57  INFO: [74D90701] connected
2016-11-09 12:26:27 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c48422c412c3130306230392c3063316131622c38303339666436352c303364$
**2016-11-09 12:26:27  INFO: [74D90701] id: 358155100054249, time: 2016-11-09 19:26:27, lat: -6.33404, lon: 107.16319, speed: 0.1, course: 0.0**
2016-11-09 12:26:32 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:26:57 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c48422c412c3130306230392c3063316133612c38303339666436352c303364$
2016-11-09 12:27:02 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:27:27 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c48422c412c3130306230392c3063316231632c38303339666436312c303364$
2016-11-09 12:27:32 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:27:33 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c43432c372e302c412c3130306230392c3063316232332c3830333966643632$
2016-11-09 12:27:57 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c48422c412c3130306230392c3063316233612c38303339666436332c303364$
2016-11-09 12:28:02 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:28:32 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:28:57 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c54582c412c3130306230392c306331633362230d0a
2016-11-09 12:29:02 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:29:27 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c54582c412c3130306230392c306331643164230d0a
2016-11-09 12:29:31 DEBUG: [74D90701: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:29:57  INFO: [74D90701] disconnected
2016-11-09 12:29:58  INFO: [E29779C4] connected
2016-11-09 12:30:02 DEBUG: [E29779C4: 5056 < 112.215.45.17] HEX: 2a45542c3335383135353130303035343234392c4d51230d0a
2016-11-09 12:30:32 DEBUG: [E297

Found some HEX line is followed by INFO line with location message, not for others. But, still don't received any data on OpenGTS database

**Comment by tananaev** [comment]
Have you restarted the service after changing config? Is it current data from the logs or some old data?

**Comment by agusu888** [comment]
not restarted yet, but traccar database didn't received data from device any more. It's new one, see on date-time

**Comment by tananaev** [comment]
Date time doesn't tell me anything because I don't know which timezone you are in. Is your server even running?

**Comment by agusu888** [comment]
just tried to restart but cannot, see below info on log file:

2016-11-09 18:02:26  INFO: Operating system name: Linux version: 3.10.0-327.36.3.el7.x86_64 architecture: amd64
2016-11-09 18:02:26  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.111-b15
2016-11-09 18:02:26  INFO: Memory limit heap: 1774mb non-heap: 0mb
2016-11-09 18:02:26  INFO: Character encoding: UTF-8 charset: UTF-8
2016-11-09 18:02:26  INFO: Version: 3.7-SNAPSHOT
2016-11-09 18:02:27  INFO: Query not provided: database.selectGroupsAll
2016-11-09 18:02:27  INFO: Query not provided: database.selectLatestPositions
2016-11-09 18:02:27  INFO: Query not provided: database.selectServers
2016-11-09 18:02:27  INFO: Query not provided: database.selectUsersAll
2016-11-09 18:02:27  INFO: Query not provided: database.selectGroupsAll
2016-11-09 18:02:27  INFO: Query not provided: database.selectGroupPermissions
2016-11-09 18:02:27  INFO: Query not provided: database.selectDevicePermissions
2016-11-09 18:02:27  INFO: Query not provided: database.selectGroupsAll
2016-11-09 18:02:27  INFO: Starting server...

**Comment by tananaev** [comment]
You should check wrapper log file.

**Comment by agusu888** [comment]
here is found at wrapper log file:
016/11/09 11:29:13 | WrapperSimpleApp Error: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets $
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:357)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2484)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2329)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       ... 26 more
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error: Caused by: java.net.UnknownHostException: [HOST]
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at java.net.InetAddress.getAllByName(InetAddress.java:1190)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at java.net.InetAddress.getAllByName(InetAddress.java:1126)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:249)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:307)
INFO   | jvm 1    | 2016/11/09 11:29:13 | WrapperSimpleApp Error:       ... 28 more
STATUS | wrapper  | 2016/11/09

**Comment by tananaev** [comment]
It looks like you lied about your config. You have `[HOST]` as a host, which should be replaced with actual value.

**Comment by tananaev** [comment]
Also, why is there 7 hours difference between two logs?

**Comment by agusu888** [comment]
i have made some correction and got following error message on tracker-server.log. Also i have added new device on openGTS refer to 'unknown device' message, but still got same.

2016-11-10 07:38:51 DEBUG: [AFA9B33B: 5084 < 185.19.217.78] HEX: 4f5054494f4e53207369703a313030403230392e35382e3138302e3937205349502f322e300d0a5669613a205349502f322e302f554450203$
2016-11-10 07:38:51 DEBUG: [AFA9B33B: 5084 > 185.19.217.78] HEX: 5e39
2016-11-10 07:38:51  WARN: Unknown device - 1330533152 (185.19.217.78)
2016-11-10 07:38:52 DEBUG: [0E671455: 5086 < 185.19.217.78] HEX: 4f5054494f4e53207369703a313030403230392e35382e3138302e3937205349502f322e300d0a5669613a205349502f322e302f554450203$
2016-11-10 07:38:52  WARN: Unknown device - ONS sip:100@209.58.1 (185.19.217.78)

**Comment by agusu888** [comment]
which conf. file to set HOST?

**Comment by tananaev** [comment]
Date in the https://github.com/tananaev/traccar/issues/2517#issuecomment-259573858 is not from your device.

Error in https://github.com/tananaev/traccar/issues/2517#issuecomment-259559108 indicates that your config is different from the one in the first comment.

**Comment by dvb-des** [comment]
2017-02-26 15:33:07  INFO: Starting server...
2017-02-26 15:33:16  INFO: [CF0E371F] connected
2017-02-26 15:33:16 DEBUG: [CF0E371F: 5027 < 46.56.180.249] HEX: 000f333533393736303133323632333032
2017-02-26 15:33:16 DEBUG: [CF0E371F: 5027 > 46.56.180.249] HEX: 01
2017-02-26 15:33:16  INFO: Query not provided: database.updateDeviceStatus
2017-02-26 15:33:27 DEBUG: [CF0E371F: 5027 < 46.56.180.249] HEX: 000000000000002908010000015a775e61ec000f113130201ee04000910008090007000200014230f801c700000000000100005685
2017-02-26 15:33:27 DEBUG: [CF0E371F: 5027 > 46.56.180.249] HEX: 00000001
2017-02-26 15:33:27  INFO: Query not provided: database.updateDeviceStatus
2017-02-26 15:33:27  WARN: Illegal mix of collations (cp1251_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '=' - SQLException (... < QueryBuilder:473 < DataManager:296 < DefaultDataHandler:27 < ...)
2017-02-26 15:33:27  INFO: Query not provided: database.updateLatestPosition
2017-02-26 15:33:27  INFO: [CF0E371F] id: 353976013262302, time: 2017-02-26 01:22:38, lat: 53.88944, lon: 25.27849, speed: 3.8, course: 8.0
2017-02-26 15:33:41  INFO: [CF0E371F] disconnected
2017-02-26 15:33:41  INFO: Query not provided: database.updateDeviceStatus
2017-02-26 15:34:40  INFO: Shutting down server...
Выдает вот такую ошибку
База opengts создана и работала с traccar 3.2. производилась полная переустановка на 3.10

**Comment by tananaev** [comment]
@dvb-des, пожалуйста создайте отдельную тему. У вас какая-то проблема с collations в базе данных.
