### ISSUE TITLE
Java ERROR

### ISSUE THREAD

**Issue by local1970** [traccar/traccar#2699]
Hi, my version is 3.7. I can not start web interface. this is wrraper.log file with errors
```
NFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Home-PC (192.168.8.49) since 11/29/16 6:44 AM
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:190)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at liquibase.Liquibase.clearCheckSums(Liquibase.java:1299)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:139)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/12/17 19:25:08 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
STATUS | wrapper  | 2016/12/17 19:25:10 | <-- Wrapper Stopped
```
Where is a problem???

**Comment by tananaev** [comment]
Looks like your database is in locked state. It usually means that you stopped the service in the middle of the database migration.

**Comment by local1970** [comment]
There is WAMP installation on the same PC. How to check locked state ???

**Comment by tananaev** [comment]
It has nothing to do with other databases. It's Liquibase migration lock.

**Comment by local1970** [comment]
I find the problem. one of Windows Media Player process work on port 5004  5005 and traccar server don`t start. When I stop that process server starts.
