### ISSUE TITLE
traccar service wont start.

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2963]
Hi,

Running traccar start wont start the traccar and I am getting following answer:
```
warning : traccar may have failed to start.

wrapper log:.......................................................
```
```
STATUS | wrapper  | 2017/02/27 21:40:16 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/02/27 21:40:16 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2017/02/27 21:40:16 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2017/02/27 21:40:16 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2017/02/27 21:40:16 | 
STATUS | wrapper  | 2017/02/27 21:40:17 | Launching a JVM...
INFO   | jvm 1    | 2017/02/27 21:40:17 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp: 
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 14; Attribute name "ll" associated with an element type "entry" must be followed by the ' = ' character.
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:76)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Properties.java:868)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at org.traccar.Config.load(Config.java:29)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:141)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 14; Attribute name "ll" associated with an element type "entry" must be followed by the ' = ' character.
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1525)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1314)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:74)
INFO   | jvm 1    | 2017/02/27 21:40:18 | WrapperSimpleApp Error: 	... 10 more
STATUS | wrapper  | 2017/02/27 21:40:20 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Your configuration file is invalid. It has to be a valid XML file.

**Comment by akmal1999** [comment]
This was working at all times. just now stopped.

**Comment by akmal1999** [comment]
does the xml file change dynamically cause I did not bring any changes...

**Comment by tananaev** [comment]
Traccar doesn't change the file, but someone must have changed it.

**Comment by akmal1999** [comment]
Hi 

I have brought no changes. Can the change happen through traccar app in Ui mode?

Where and how can we change this back to fix this?

Thanks

**Comment by tananaev** [comment]
There is absolutely no chance that Traccar changed it. You need to fix the problem. Check the error message for more details. It has exact position in the config.

**Comment by akmal1999** [comment]
Which config file is this referring to?

**Comment by tananaev** [comment]
Not sure. You should check both.
