### ISSUE TITLE
Unable to start Traccar - Geofence error

### ISSUE THREAD

**Issue by deathg0d** [traccar/traccar#3081]
A BIG EDIT: Actually the rate was only giving us a warning. But the server not starting at all was caused by something else. It seems to be an error with the geofences:

```
STATUS | wrapper  | 2017/04/09 12:58:06 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/04/09 12:58:06 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2017/04/09 12:58:06 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2017/04/09 12:58:06 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2017/04/09 12:58:06 |
STATUS | wrapper  | 2017/04/09 12:58:06 | Launching a JVM...
INFO   | jvm 1    | 2017/04/09 12:58:06 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/04/09 12:58:07 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2017/04/09 12:58:08 | INFO 4/9/17 12:58 PM: liquibase: Clearing database change log checksums
INFO   | jvm 1    | 2017/04/09 12:58:08 | INFO 4/9/17 12:58 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2017/04/09 12:58:08 | INFO 4/9/17 12:58 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2017/04/09 12:58:08 | INFO 4/9/17 12:58 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2017/04/09 12:58:09 | INFO 4/9/17 12:58 PM: liquibase: Reading from traccar.DATABASECHANGELOG
INFO   | jvm 1    | 2017/04/09 12:58:09 | INFO 4/9/17 12:58 PM: liquibase: Reading from traccar.DATABASECHANGELOG
INFO   | jvm 1    | 2017/04/09 12:58:09 | INFO 4/9/17 12:58 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2017/04/09 12:58:10 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @3432ms
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp:
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at org.traccar.database.GeofenceManager.refresh(GeofenceManager.java:144)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at org.traccar.database.GeofenceManager.<init>(GeofenceManager.java:56)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:204)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:30)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2017/04/09 12:58:10 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2017/04/09 12:58:12 | <-- Wrapper Stopped
```

Seems like there was an error with geofence which is stopping the server from running. When the server was running before it stopped it was giving some null pointer exception error while marking new geofences.

----------------------------------------------------------------

Please ignore the old comment below >>
My traccar server does not seem to start at all. I get the following warning when I try to start the server. I have tried the `resetDelay` as discussed in other issues but I still cannot seem to start the server. It starts and then after a few seconds it stops. I am using 5022 and 5023 for tracking and don't have many devices - around 10 in each.

```INFO   | jvm 1    | 2017/04/09 00:00:16 | Apr 09, 2017 12:00:16 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2017/04/09 00:00:16 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2017/04/09 00:00:16 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2017/04/09 00:00:16 |       at org.jboss.netty.channel.soc

**Comment by tananaev** [comment]
The problem is that you reached the limit of open files. Check this page for more info:

https://www.traccar.org/optimization/

**Comment by deathg0d** [comment]
@tananaev Hi sorry. It wasn't the limit that was causing the server to not start. It was a geofence error. Could please recheck my question above? Thanks

**Comment by tananaev** [comment]
Looks like you have some problem with database. What database are you using? If MySQL, what engine?

**Comment by deathg0d** [comment]
@tananaev It was working fine for few weeks. Here's how the problem started:

While we were entering new geofences somehow (not sure how yet) a null value row got inserted to the geofences table. Then every time we wanted to add another geofence, it gave us a popup error saying null pointer exception. Then on next restart Traccar would stop right away giving the above mentioned error. Now I am unable to start Traccar at all.

**Comment by tananaev** [comment]
I guess there is still some dangling reference in the database.

**Comment by deathg0d** [comment]
@tananaev I have checked all tables and rows on the mysql database. There doesn't seem to be any reference out of place :(

**Comment by tananaev** [comment]
I can take a look if you provide me an access to the database.

**Comment by deathg0d** [comment]
@tananaev Hi, I managed to fix this issue. The issue originated somehow because `group` and `group_geofence` tables were empty. I filled it with some values and everything is now working as it should. I don't understand how it suddenly stopped working though. It was working fine before when the tables were empty.

**Comment by tananaev** [comment]
What database are you using?

**Comment by deathg0d** [comment]
@tananaev mysql

**Comment by tananaev** [comment]
Are you using MyISAM engine by any chance? That would be the reason why you experience problems like this. You have to use InnoDB engine.
