### ISSUE TITLE
Server halts

### ISSUE THREAD

**Issue by matejkramny** [traccar/traccar#3143]
error log excerpt, which was ~3gb.

```
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
FINEST|1911/0|Service traccar|17-05-02 18:07:52|java.io.IOException: Too many open files
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|	at java.lang.Thread.run(Thread.java:745)
FINEST|1911/0|Service traccar|17-05-02 18:07:52|[qtp450589816-32-acceptor-0@7b630908-ServerConnector@75a4f814{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
```

What's the best way to fix?

Thanks!

**Comment by tananaev** [comment]
Please read this:

https://www.traccar.org/optimization/
