### ISSUE TITLE
Traccar server ChannelExcetion

### ISSUE THREAD

**Issue by vijaemanlapaz** [traccar/traccar#3291]
Hi i'm very clueless about this error
It would be nice if you can shed a light on this.

```
INFO|11328/0|Service traccar|17-06-25 18:23:33|Caused by: java.net.BindException: Address already in use
INFO|11328/0|Service traccar|17-06-25 18:23:33|	at sun.nio.ch.Net.bind0(Native Method)
INFO|11328/0|Service traccar|17-06-25 18:23:33|	at sun.nio.ch.Net.bind(Net.java:433)
INFO|11328/0|Service traccar|17-06-25 18:23:33|	at sun.nio.ch.Net.bind(Net.java:425)
INFO|11328/0|Service traccar|17-06-25 18:23:33|	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO|11328/0|Service traccar|17-06-25 18:23:34|	at java.lang.Thread.run(Thread.java:745)
INFO|wrapper|Service traccar|17-06-25 18:23:35|waitpid 11328 59136
INFO|wrapper|Service traccar|17-06-25 18:23:35|exit code posix process: 59136 application: 0
```

**Comment by tananaev** [comment]
The problem is that you have a port conflict with some other process.
