### ISSUE TITLE
Issue with generating large reports

### ISSUE THREAD

**Issue by socstur** [traccar/traccar#3404]
Anyone getting this error below when generating a large report? I have about 20 devices and when I try to do a monthly summary report I get this error below. Doing a monthly route report  of a single device also generates this error. I'm assuming its the size of the report since I can reduce the number of days and I don't get any error. Anyone run into this issue and is there a way around it?
```
FINEST|674/0|Service traccar|17-07-31 13:53:23|Jul 31, 2017 1:53:23 PM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
FINEST|674/0|Service traccar|17-07-31 13:53:23|SEVERE: An I/O error has occurred while writing a response message entity to the container output stream.
FINEST|674/0|Service traccar|17-07-31 13:53:23|org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.Server.handle(Server.java:499)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at java.lang.Thread.run(Thread.java:748)
FINEST|674/0|Service traccar|17-07-31 13:53:23|Caused by: org.eclipse.jetty.io.EofException
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectChannelEndPoint.onSelected(SelectChannelEndPoint.java:111)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:641)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:612)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
FINEST|674/0|Service traccar|17-07-31 13:53:23| ... 3 more
FINEST|674/0|Service traccar|17-07-31 13:53:23|Caused by: java.io.IOException: Broken pipe
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.Server.handle(Server.java:499)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at java.lang.Thread.run(Thread.java:748)
FINEST|674/0|Service traccar|17-07-31 13:53:23|Caused by: org.eclipse.jetty.io.EofException
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectChannelEndPoint.onSelected(SelectChannelEndPoint.java:111)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:641)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:612)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
FINEST|674/0|Service traccar|17-07-31 13:53:23| ... 3 more
FINEST|674/0|Service traccar|17-07-31 13:53:23|Caused by: java.io.IOException: Broken pipe
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.IOUtil.write(IOUtil.java:65)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
FINEST|674/0|Service traccar|17-07-31 13:53:23| at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
FINEST|674/0|Service traccar|17-07-31 13:53:23| ... 10 more
FINEST|674/0|Service traccar|17-07-31 13:53:23|
```

**Comment by tananaev** [comment]
I believe it's caused by timeout in browser. Report takes too long to load, so your browser closes connection.

**Comment by socstur** [comment]
Any ideas on how this can be resolved?  A speed up on the server side so the reporting doesn't take as long? or anything that can be done to the traccar code to resolve the problem?

**Comment by tananaev** [comment]
Options:

1. Faster server so that reports are generated in less time
2. Increase browser timeout (not all browsers support it and also requires user action)
3. Change the way we generate reports (requires significant code changes)

**Comment by socstur** [comment]
I read around the forums and GitHub that traccar has been tested with a much larger number of devices. Did you guys run into this problem generating large reports for them? If not then I'll need to look more into option 1 and get the correct system specs to handle it.

**Comment by tananaev** [comment]
Traccar has been tested with thousands of devices, but generating reports for a big number of devices will always take a long time. I don't see any reason for generating reports for thousands of devices in one go. Maybe a few hundred devices, and even that only makes sense for summary report.

**Comment by socstur** [comment]
Hi Anton,
               I'm only generating a monthly summary report for 20 devices. I'm running a VPS using 4 cores of Intel(R) Xeon(R) CPU E5-2670 @ 2.60GHz, 30GB SSD storage, and 6GB of ram.  Do you think this should work?

**Comment by socstur** [comment]
Hi Anton,
               I'm only generating a monthly summary report for 20 devices. I'm running a VPS using 4 cores of Intel(R) Xeon(R) CPU E5-2670 @ 2.60GHz, 30GB SSD storage, and 6GB of ram.  Do you think this should work?

**Comment by tananaev** [comment]
It depends on...

1. Have you configured server and database to utilise all resources?
2. What database are you using? Is it up-to-date and configured properly?
3. How often do devices report data. For example if it's every second, that's a massive amount of data even for 20 devices.
4. How many other devices and users are on your server? Obviously overall server load will affect your reports as well.

**Comment by socstur** [comment]
Hi Anton,
              I am using mysql database. Can you shed some more light on 1) Have you configured server and database to utilise all resources? With traccar written in Java does it use the four cores available to it or does it run only on single core?

Regards,

**Comment by tananaev** [comment]
Traccar will use all available cores, not for a single report though. I was talking about memory utilisation.

**Comment by socstur** [comment]
Thanks Anton...I did a some  optimization on mysql server and now I'm able to do up to 2 weeks summary report on my 20 devices. 

It looks to me it'll take a lot of time to generate these large reports  (ie monthly or quarterly) with the way the reports are generated and sent over the web. Do you think it is worthwhile for the team to look into how these large reports are generated and sent across the web? Maybe generate and send them in piece-meal? I noticed the summary report is already separated by device.

**Comment by tananaev** [comment]
The easiest option I can think of is to send an email with Excel report when it's complete.

**Comment by tsmgeek** [comment]
I have done quite a bit of work with CSV data parsing/writing which can be a pain.
I looked at the class and seems you are writing it into memory, why not do the following.

Open a temp filehandle and push all the data straight out to that, this will get over memory issues from writing the file, if the issue is a single large DB query then it would need to be an unbuffered query (not sure if this can be done in H2 db) so as not to allocate all the space for the DB result in one go. If unbuffered can not be done then splitting the query down, ie do count first on query then LIMIT though the result set as its processed.

 when job is complete use WS to indicate to browser that job is complete and they can download the report and/or email file/link to user account.

ps. Also why does traccar not use a dedicated CSV writing library? I have come across so many issues with people trying to handle escaping themselves.

**Comment by tananaev** [comment]
@tsmgeek, there are no CSV files or memory issues.

**Comment by tsmgeek** [comment]
Just checked the exporter code and was looking at the CSV library that was in the api by mistake.

**Comment by gpproton** [comment]
> The easiest option I can think of is to send an email with Excel report when it's complete.

Hi @tananaev is there any chance this would be implemented anytime soon, i'm currently using a custom php web application pull months of data for up to 1000 devices even if it not the most comfortable solution for users using 2 sites.

**Comment by tananaev** [comment]
Send me an email to discuss it.
