### ISSUE TITLE
Uncaught Exception by Thread

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3750]
I had this show in the logs and trying to work out what happened.
It seems that at the point the exception was flagged the webui continued working then slowly as devices disconnected they would no longer reconnect to the point that nothing was being tracked at about 22:13 the same day as the exception.
Loads of IOExceptions started to appear 15mins after the exception but then stop after a few seconds, may not be related though.

tracker-server
```
2018-01-30 18:32:32  WARN: [95F5ECE8] error - Connection reset by peer - IOException (...)
2018-01-30 18:32:32  INFO: [95F5ECE8] disconnected
2018-01-30 18:32:36  WARN: [EBACAE52] error - Connection reset by peer - IOException (...)
2018-01-30 18:32:36  INFO: [EBACAE52] disconnected
2018-01-30 18:32:36  WARN: [7D655456] error - Connection reset by peer - IOException (...)
2018-01-30 18:32:36  INFO: [7D655456] disconnected
2018-01-30 18:32:37  WARN: [BD94FC31] error - Connection reset by peer - IOException (...)
2018-01-30 18:32:37  INFO: [BD94FC31] disconnected
2018-01-30 18:32:38  WARN: [3799F027] error - Connection reset by peer - IOException (...)
2018-01-30 18:32:38  INFO: [3799F027] disconnected
2018-01-30 18:32:38  WARN: [053D684C] error - Connection reset by peer - IOException (...)
```
wrapper
```
> INFO|30489/0|Service traccar|18-01-30 18:13:33|Uncaught exception by Thread[pool-5-thread-1,5,main]:
> INFO|30489/0|Service traccar|18-01-30 18:13:33|java.lang.InternalError:java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64/jre/lib/ext/localedata.jar
> INFO|30489/0|Service traccar|18-01-30 18:13:33|java.lang.InternalError: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64/jre/lib/ext/localedata.jar
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1040)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.security.AccessController.doPrivileged(Native Method)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle$RBClassLoader.loadClass(ResourceBundle.java:503)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2640)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.Level.computeLocalizedLevelName(Level.java:265)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.Level.getLocalizedLevelName(Level.java:324)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.SimpleFormatter.format(SimpleFormatter.java:165)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.Logger.log(Logger.java:738)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.Logger.doLog(Logger.java:765)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.logging.Logger.logp(Logger.java:1042)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at org.jboss.netty.logging.JdkLogger.warn(JdkLogger.java:80)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:340)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.lang.Thread.run(Thread.java:748)
> INFO|30489/0|Service traccar|18-01-30 18:13:33|Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64/jre/lib/ext/localedata.jar
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:928)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:791)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:876)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:869)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at java.security.AccessController.doPrivileged(Native Method)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:868)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1038)
> INFO|30489/0|Service traccar|18-01-30 18:13:33| ... 31 more
```

**Comment by tananaev** [comment]
I don't think those two things are related. Looks like your devices disconnect on their own. As for wrapper log, it indicates that you have some issue with JVM.
