### ISSUE TITLE
How to add new protocol with port on vps server?

### ISSUE THREAD

**Issue by sagar1351** [traccar/traccar#3763]
we added two files in a protocol folder with protocol and its decoder file(java files). also made entry in default.xml file like other protocol entry.
Build this project with intellij idea.
i upload jar file server but it gives errors.

```
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperSimpleApp Error: Unable to locate the class org.traccar.Main : java.lang.ClassNotFoundException: org.traccar.Main
jvm 1    | 
jvm 1    | WrapperSimpleApp Usage:
jvm 1    | WrapperManager Error: Error in WrapperListener.start callback.  java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
jvm 1    | WrapperManager Error: java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
jvm 1    | WrapperManager Error:   at java.text.MessageFormat.makeFormat(MessageFormat.java:1430)
jvm 1    | WrapperManager Error:   at java.text.MessageFormat.applyPattern(MessageFormat.java:480)
jvm 1    | WrapperManager Error:   at java.text.MessageFormat.<init MessageFormat.java:364)
jvm 1    | WrapperManager Error:   at java.text.MessageFormat.format(MessageFormat.java:841)
jvm 1    | WrapperManager Error:   at org.tanukisoftware.wrapper.WrapperResources.getString(WrapperResources.java:194)
jvm 1    | WrapperManager Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.showUsage(WrapperSimpleApp.java:597)
jvm 1    | WrapperManager Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.start(WrapperSimpleApp.java:441)
jvm 1    | WrapperManager Error:   at org.tanukisoftware.wrapper.WrapperManager$10.run(WrapperManager.java:4241)
jvm 1    | WrapperManager Error: Caused by: java.lang.NumberFormatException: For input string: "app_class{/app_method}"
jvm 1    | WrapperManager Error:   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
jvm 1    | WrapperManager Error:   at java.lang.Integer.parseInt(Integer.java:492)
jvm 1    | WrapperManager Error:   at java.lang.Integer.parseInt(Integer.java:527)
jvm 1    | WrapperManager Error:   at java.text.MessageFormat.makeFormat(MessageFormat.java:1428)
jvm 1    | WrapperManager Error:   ... 7 more
wrapper  | <— Wrapper Stopped
```

Its working on localhost 8082 but not on vps server.

**Comment by tananaev** [comment]
Why are you using Java Service Wrapper? Traccar doesn't use it anymore.

**Comment by sagar1351** [comment]
@tananaev -  Is  there any alternative for java service wrapper?And when i build this its working on localhost.

**Comment by tananaev** [comment]
We use YAJSW. As for the error, it probably means that something is wrong with your build. I would recommend using maven instead of intellij to build final result.

**Comment by tananaev** [comment]
We're not using either now. We implemented service natively in Traccar.
