### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by crispjava** [traccar/traccar#3933]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/SessionCookieConfig
	at org.traccar.web.WebServer.<init>(WebServer.java:80)
	at org.traccar.Context.init(Context.java:383)
	at org.traccar.Main.main(Main.java:35)
Caused by: java.lang.ClassNotFoundException: javax.servlet.SessionCookieConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1

**Comment by tananaev** [comment]
What version of Java are you using? Try 8.
