### ISSUE TITLE
Inflated Wrapper

### ISSUE THREAD

**Issue by tyepez** [traccar/traccar#3935]
Hi, 

Please help me.
I always have this problem, the server works well, and after several months it falls down, throwing the following errors.

```
FINEST|2756/0|Service traccar|18-06-14 00:00:00|Jun 14, 2018 12:00:00 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
FINEST|2756/0|Service traccar|18-06-14 00:00:00|WARNING: Failed to accept a connection.
FINEST|2756/0|Service traccar|18-06-14 00:00:00|java.io.IOException: Too many open files
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|        at java.lang.Thread.run(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:00|
FINEST|2756/0|Service traccar|18-06-14 00:00:01|Jun 14, 2018 12:00:01 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
FINEST|2756/0|Service traccar|18-06-14 00:00:01|WARNING: Failed to accept a connection.
FINEST|2756/0|Service traccar|18-06-14 00:00:01|java.io.IOException: Too many open files
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|        at java.lang.Thread.run(Unknown Source)
FINEST|2756/0|Service traccar|18-06-14 00:00:01|
```

```
[root@gps logs]# ll -h
total 16G
-rw-rw-rw- 1 root root 1.3M Jun 14 19:50 tracker-server.log
-rw-rw-rw- 1 root root 5.9M Apr  6 23:59 tracker-server.log.20180406
...
-rw-rw-rw- 1 root root 1.6K Jun 11 14:19 wrapper.log.20180611
-rw-rw-rw- 1 root root  399 Jun 12 13:15 wrapper.log.20180612
-rw-rw-rw- 1 root root 5.9G Jun 13 23:59 wrapper.log.20180613
-rw-rw-rw- 1 root root 8.9G Jun 14 20:09 wrapper.log.20180614
-rw-rw-rw- 1 root root    0 Jun 14 00:00 wrapper.log.20180614.lck
```

**Comment by tananaev** [comment]
It has been discussed many times. I would recommend you to read this:

https://www.traccar.org/optimization/
