### ISSUE TITLE
[BUG REPORT] SQL Server - Fresh Database Creation failure

### ISSUE THREAD

**Issue by psavva** [traccar/traccar#4016]
Dear Team, 

I have installed SQL Server, and also installed Traccar.
I have successfully configured Traccar to connect to the SQL Server.

Upon starting the service for the 1st time, the Traccar Service will stop given the following error in the log:

```
FINEST|4052/0|Service traccar|18-08-18 12:30:20|java.lang.reflect.InvocationTargetException
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at java.lang.reflect.Method.invoke(Unknown Source)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-4.0::changelog-4.0::author:
FINEST|4052/0|Service traccar|18-08-18 12:30:20|     Reason: liquibase.exception.DatabaseException: The object 'DF_notifications_web' is dependent on column 'web'. [Failed SQL: ALTER TABLE tc_notifications DROP COLUMN web]
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.Liquibase.update(Liquibase.java:202)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.Liquibase.update(Liquibase.java:179)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.Liquibase.update(Liquibase.java:175)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:307)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.traccar.database.DataManager.<init>(DataManager.java:88)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.traccar.Context.init(Context.java:361)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at org.traccar.Main.main(Main.java:35)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	... 6 more
FINEST|4052/0|Service traccar|18-08-18 12:30:20|Caused by: liquibase.exception.DatabaseException: The object 'DF_notifications_web' is dependent on column 'web'. [Failed SQL: ALTER TABLE tc_notifications DROP COLUMN web]
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	... 15 more
FINEST|4052/0|Service traccar|18-08-18 12:30:20|Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The object 'DF_notifications_web' is dependent on column 'web'.
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:857)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:757)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7347)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:734)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
FINEST|4052/0|Service traccar|18-08-18 12:30:20|	... 20 more
```

Info from the Traccar Server Log:
```
2018-08-18 12:30:15  INFO: Operating system name: Windows Server 2008 R2 version: 6.1 architecture: amd64
2018-08-18 12:30:15  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.181-b13
2018-08-18 12:30:15  INFO: Memory limit heap: 2729mb non-heap: 0mb
2018-08-18 12:30:15  INFO: Character encoding: UTF-8 charset: UTF-8
2018-08-18 12:30:15  INFO: Version: 4.0-SNAPSHOT
```

The ZIP File attached is a FULL BACKUP of the TRACCAR Database (NO Data as this is a fresh installation)
[Traccar.zip](https://github.com/traccar/traccar/files/2299332/Traccar.zip)

You should be able to run a Restore on Microsoft SQL Server Manager if you wish to import the database and review it's structure, and understand the state of the database.

Let me know if you need any further info, and will be happy to provide.

You should also easily be able to replicate by following the same steps:
Download traccar and install
Create MS SQL Database for Traccar
Update config file to point to the Traccar Database

Start Traccar.

Review the Logs from Traccar.  [provided you connected successfully and started creating db objects to start off with :)  ]

Full Log files attached:
[traccarlogs.zip](https://github.com/traccar/traccar/files/2299337/traccarlogs.zip)

**Comment by psavva** [comment]
As I understand the problem, I have dropped the 3 columns from tc_notifications (web, sms, mail), and removed the changeset from changelog-4.0.xml of the migration and dropping of columns.

I left the creation of the new column notificators in place of course :)

Traccar start up properly now.
I hope this information is useful to fix the data migration issue.

**Comment by tananaev** [comment]
It's already fixed. See #3993.
