### ISSUE TITLE
Service keeps stopping

### ISSUE THREAD

**Issue by xspid3r** [traccar/traccar#4054]
i'm having a problem when i start the service it stops after a few seconds

here is the wrapper log:

```
STATUS | wrapper  | 2018/09/16 01:53:43 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2018/09/16 01:53:43 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2018/09/16 01:53:43 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2018/09/16 01:53:43 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2018/09/16 01:53:43 | 
WARN   | wrapper  | 2018/09/16 01:53:43 | The value of wrapper.java.command does not appear to be a java binary.
WARN   | wrapper  | 2018/09/16 01:53:43 | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
STATUS | wrapper  | 2018/09/16 01:53:43 | Launching a JVM...
INFO   | jvm 1    | 2018/09/16 01:53:43 | WrapperManager: Initializing...
INFO   | jvm 1    | 2018/09/16 01:53:45 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @1101ms
INFO   | jvm 1    | 2018/09/16 01:53:45 | [Thread-1] INFO org.eclipse.jetty.server.Server - jetty-9.2.z-SNAPSHOT
INFO   | jvm 1    | 2018/09/16 01:53:47 | [Thread-1] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@3034f22{/api,null,AVAILABLE}
INFO   | jvm 1    | 2018/09/16 01:53:47 | [Thread-1] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED ServerConnector@5cdca7d1{HTTP/1.1}{0.0.0.0:8082}: java.net.BindException: Address already in use
INFO   | jvm 1    | 2018/09/16 01:53:47 | java.net.BindException: Address already in use
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind(Net.java:463)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind(Net.java:455)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.web.WebServer.start(WebServer.java:197)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main.initServer(Main.java:111)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main.access$100(Main.java:30)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main$2.run(Main.java:100)
INFO   | jvm 1    | 2018/09/16 01:53:47 | [Thread-1] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@387de9e3: java.net.BindException: Address already in use
INFO   | jvm 1    | 2018/09/16 01:53:47 | java.net.BindException: Address already in use
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind(Net.java:463)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.Net.bind(Net.java:455)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.web.WebServer.start(WebServer.java:197)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main.initServer(Main.java:111)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main.access$100(Main.java:30)
INFO   | jvm 1    | 2018/09/16 01:53:47 | 	at org.traccar.Main$2.run(Main.java:100)
STATUS | wrapper  | 2018/09/16 01:54:18 | TERM trapped.  Shutting down.
INFO   | jvm 1    | 2018/09/16 01:54:19 | [Thread-12] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@5cdca7d1{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2018/09/16 01:54:19 | [Thread-12] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@3034f22{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2018/09/16 01:54:19 | <-- Wrapper Stopped
INFO   | jvm 1    | 2018/09/16 01:56:08 | [pool-3-thread-1] WARN io.netty.util.HashedWheelTimer - An exception was thrown by TimerTask.
INFO   | jvm 1    | 2018/09/16 01:56:08 | redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.jedis.Protocol.process(Protocol.java:151)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.jedis.Protocol.read(Protocol.java:215)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.jedis.Jedis.del(Jedis.java:197)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at org.traccar.database.RedisManager.removeDevice(RedisManager.java:57)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at org.traccar.database.ConnectionManager.updateDevice(ConnectionManager.java:97)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at org.traccar.database.ConnectionManager$1.run(ConnectionManager.java:132)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2018/09/16 01:56:08 | Caused by: java.net.SocketTimeoutException: Read timed out
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at java.net.SocketInputStream.socketRead0(Native Method)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at java.net.SocketInputStream.read(SocketInputStream.java:153)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at java.net.SocketInputStream.read(SocketInputStream.java:108)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
INFO   | jvm 1    | 2018/09/16 01:56:08 | 	... 13 more


```

**Comment by tananaev** [comment]
You have a port conflict.

**Comment by xspid3r** [comment]
How would i know which port is it and how do i fix it please?

**Comment by xspid3r** [comment]
@tananaev How would i know which port is it and how do i fix it please?

**Comment by tananaev** [comment]
It's web port. You need to either change port or stop other process from using it.
