### ISSUE TITLE
Support Java 11 64bit.. traccar Version traccar-windows-4.0.zip	05-Aug-2018?

### ISSUE THREAD

**Issue by EOM** [traccar/traccar#4087]
Hi,
Support Java 11 64bit traccar Version traccar-windows-4.0.zip	05-Aug-2018?

Print error: https://i.postimg.cc/RCtPC0tQ/print_de_pantalla_737.jpg

Out:
```
C:\Program Files\Traccar\bat>startService.bat

C:\Program Files\Traccar\bat>pushd C:\Program Files\Traccar\bat\

C:\Program Files\Traccar\bat>call setenv.bat
"java" -Xmx30m -Dwrapper_home="C:\Program Files\Traccar\bat\/.." -Djna_tmpdir="C:\Program Files\Traccar\bat\/../tmp" -Djava.net.preferIPv4Stack=true -jar "C:\Program Files\Traccar\bat\/../wrapper.jar" -t "C:\Program Files\Traccar\bat\/../conf/wrapper.conf"
YAJSW: yajsw-stable-12.12
OS   : Windows 10/10.0/amd64
JVM  : Oracle Corporation/11/C:\Program Files\Java\jdk-11/64
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: Acceso denegado
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at org.rzo.yajsw.os.ms.win.w32.WindowsXPProcess$MyKernel32.<clinit>(WindowsXPProcess.java:305)
        at org.rzo.yajsw.os.ms.win.w32.WindowsXPProcess.changeWorkingDir(WindowsXPProcess.java:4150)
        at org.rzo.yajsw.os.ms.win.w32.OperatingSystemWindowsXP.setWorkingDir(OperatingSystemWindowsXP.java:127)
        at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:115)
        ... 5 more

C:\Program Files\Traccar\bat>
```

**Comment by tananaev** [comment]
Don't use Java 11 with 4.0. It's not supported. Use Java 8.

**Comment by tananaev** [comment]
It will be supported with next release.

**Comment by EOM** [comment]
OK ;-(
