### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by flocsy** [traccar/traccar#4229]
https://github.com/traccar/traccar/commit/cb4ba475c71cd83a2bde40938216b55e8f686207 broke the build:

```
2019-02-22 00:40:14 ERROR: Main method error - Unable to create injector, see the following errors:

1. A binding to java.lang.String annotated with @com.google.inject.assistedinject.Assisted(value=) was already configured at org.traccar.WebDataHandler$Factory.create().
   at org.traccar.WebDataHandler$Factory.create(WebDataHandler.java:1)
   at com.google.inject.assistedinject.FactoryProvider2.initialize(FactoryProvider2.java:716)
   at org.traccar.MainModule.configure(MainModule.java:45) (via modules: org.traccar.MainModule -> com.google.inject.assistedinject.FactoryModuleBuilder$1)

1 error - CreationException (... < Main:111 < *:104)
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1. A binding to java.lang.String annotated with @com.google.inject.assistedinject.Assisted(value=) was already configured at org.traccar.WebDataHandler$Factory.create().
   at org.traccar.WebDataHandler$Factory.create(WebDataHandler.java:1)
   at com.google.inject.assistedinject.FactoryProvider2.initialize(FactoryProvider2.java:716)
   at org.traccar.MainModule.configure(MainModule.java:45) (via modules: org.traccar.MainModule -> com.google.inject.assistedinject.FactoryModuleBuilder$1)

1 error
at org.traccar.Main.run(Main.java:152)
at org.traccar.Main.main(Main.java:104)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1. A binding to java.lang.String annotated with @com.google.inject.assistedinject.Assisted(value=) was already configured at org.traccar.WebDataHandler$Factory.create().
   at org.traccar.WebDataHandler$Factory.create(WebDataHandler.java:1)
   at com.google.inject.assistedinject.FactoryProvider2.initialize(FactoryProvider2.java:716)
   at org.traccar.MainModule.configure(MainModule.java:45) (via modules: org.traccar.MainModule -> com.google.inject.assistedinject.FactoryModuleBuilder$1)

1 error
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
at com.google.inject.Guice.createInjector(Guice.java:87)
at com.google.inject.Guice.createInjector(Guice.java:69)
at com.google.inject.Guice.createInjector(Guice.java:59)
at org.traccar.Main.run(Main.java:111)
... 1 more
Disconnected from the target VM, address: '127.0.0.1:42173', transport: 'socket'
```

**Comment by tananaev** [comment]
Fixed, thanks for reporting. Please next time don't duplicate your message though.
