### ISSUE TITLE
server wont start 

### ISSUE THREAD

**Issue by icf20** [traccar/traccar#4334]
```
java -jar tracker-server.jar conf/traccar.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/traccar/lib/slf4j-jdk14-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/traccar/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
2019-06-20 07:09:35 ERROR: Main method error - The element type "entry" must be terminated by the matching end-tag "</entry>". - SAXParseException (... < Config:37 < Context:269 < Main:110 < ...)
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Configuration file is not a valid XML document
        at org.traccar.Main.run(Main.java:152)
        at org.traccar.Main.main(Main.java:104)
Caused by: java.lang.RuntimeException: Configuration file is not a valid XML document
        at org.traccar.config.Config.<init>(Config.java:52)
        at org.traccar.Context.init(Context.java:269)
        at org.traccar.Main.run(Main.java:110)
        ... 1 more
Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 3; The element type "entry" must be terminated by the matching end-tag "</entry>".
        at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
        at java.util.Properties$XmlSupport.load(Properties.java:1201)
        at java.util.Properties.loadFromXML(Properties.java:881)
        at org.traccar.config.Config.<init>(Config.java:37)
        ... 3 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 3; The element type "entry" must be terminated by the matching end-tag "</entry>".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
        at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)

```

**Comment by tananaev** [comment]
Your config is invalid. For questions you should use forum.

**Comment by icf20** [comment]
for anyone reading yes that was the issue for some reason nano dont like copy paste (from another file) i will have to make a note note and  only use move file next time
