### ISSUE TITLE
Traccar won't start (Could not acquire change log lock.)

### ISSUE THREAD

**Issue by Preisschild** [traccar/traccar#4339]
My Traccar won't start anymore. 
I think this is possible related to #2047 but I couldnt figure the solution out.
My database is H2. 
I have zero experience with that, but would still like to use my old database instead of starting a new one.

```
Exception in thread "main" java.lang.RuntimeException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by traccar (172.17.0.6) since 6/26/19 12:48 PM
	at org.traccar.Main.run(Main.java:152)
	at org.traccar.Main.main(Main.java:104)
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by traccar (172.17.0.6) since 6/26/19 12:48 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:230)
	at liquibase.Liquibase.clearCheckSums(Liquibase.java:1442)
	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:310)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:292)
	at org.traccar.Main.run(Main.java:110)
	... 1 more
```

**Comment by tananaev** [comment]
This is a common issue. It has been discussed many times on the forum. You should search there. Also, if you have any other problems, use forum instead of GitHub.
