### ISSUE TITLE
IndexOutOfBoundsException sametimes when Teltonika tracker sends buffred data

### ISSUE THREAD

**Issue by fordsman** [traccar/traccar#4455]
Get this sometimes when power on Teltonika FMB122/202, cpu-reset of device solves often the problem but not all the times.
/Johan F
```
2019-12-11 18:17:02  INFO: [9009ae2a: teltonika < 18.197.48.88] HEX: 00000000000004d1081e0000016ef5f64f0501000000000000000000000000000000f70401f7040311029312ff1513ff2a00000000016ef5f64efb01000000000000000000000000000000f70401f7040311029512ff1713ff1e00000000016ef5f64ef101000000000000000000000000000000f70401f7040311029312ff1f13ff0f00000000016ef5f64ee701000000000000000000000000000000f70401f7040311029b12ff1e13ff0f00000000016ef5f64edd01000000000000000000000000000000f70401f704031102a112ff0b13ff1700000000016ef5f64ed301000000000000000000000000000000f70401f704031102a712fefb13ff1500000000016ef5f64ec901000000000000000000000000000000f70401f704031102a812fef713ff0d00000000016ef5f64ebf01000000000000000000000000000000f70401f704031102a112fefe13ff0a00000000016ef5f64eb501000000000000000000000000000000f70401f704031102a512ff0713ff0300000000016ef5f64eab01000000000000000000000000000000f70401f704031102ae12ff0a13feff00000000016ef5f64ea101000000000000000000000000000000f70401f704031102b412ff0113ff0300000000016ef5f64e9701000000000000000000000000000000f70401f704031102af12ff0513ff0400000000016ef5f64e8d01000000000000000000000000000000f70401f704031102ae12ff0813ff0a00000000016ef5f64e8301000000000000000000000000000000f70401f704031102a112ff0c13ff0a00000000016ef5f64e7901000000000000000000000000000000f70401f7040311029a12ff0513ff1000000000016ef5f64e6f01000000000000000000000000000000f70401f704031102a012fefc13ff1800000000016ef5f64e6501000000000000000000000000000000f70401f704031102a712fefa13ff0c00000000016ef5f64e5b01000000000000000000000000000000f70401f704031102af12fef813ff0600000000016ef5f64e5101000000000000000000000000000000f70401f704031102a912fef813ff0500000000016ef5f64e4701000000000000000000000000000000f70401f704031102a412fefb13ff0700000000016ef5f64e3d01000000000000000000000000000000f70401f704031102a212fef713ff0900000000016ef5f64e3301000000000000000000000000000000f70401f704031102a012fef813ff0c00000000016ef5f64e2901000000000000000000000000000000f70401f7040311029b12fefa13ff0c00000000016ef5f64e1f01000000000000000000000000000000f70401f704031102a012fefc13ff1300000000016ef5f64e1501000000000000000000000000000000f70401f70403
2019-12-11 18:17:02  INFO: [9009ae2a: teltonika < 18.197.48.88] HEX: 11029e12fefa13ff1f00000000016ef5f64e0b01000000000000000000000000000000f70401f7040311029b12ff0513ff1c00000000016ef5f64e0101000000000000000000000000000000f70401f7040311029b12ff1413ff1700000000016ef5f64df701000000000000000000000000000000f70401f7040311029b12ff2313ff0c00000000016ef5f64ded01000000000000000000000000000000f70401f7040311029e12ff2713feff00000000016ef5f64de301000000000000000000000000000000f70401f704031102a712ff2513fef800001e0000dd53
2019-12-11 18:17:02  WARN: [9009ae2a] error - 
java.lang.IndexOutOfBoundsException: readerIndex(1238) + length(8) exceeds writerIndex(1245): PooledSlicedByteBuf(ridx: 1238, widx: 1245, cap: 1245/1245, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1245, widx: 1245, cap: 2048))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1451)
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:843)
	at org.traccar.protocol.TeltonikaProtocolDecoder.readValue(TeltonikaProtocolDecoder.java:191)
	
2019-12-11 18:17:02  INFO: [9009ae2a] disconnected
```

**Comment by tananaev** [comment]
Sounds like a device issue to me, but could also be non-standard protocol.

**Comment by tananaev** [comment]
Need the documentation and ideally a breakdown to investigate this, if it still happens.

**Comment by sibieta** [comment]
Have similar issue, tried using the TeltonikaProtocolDecodeTest and added this code where i try to decode the server string to be decoded

`/*PRUEBA SIMPLEDATA */
        System.out.print("SIMPLEDATA");
        String framesd = "00000000000004d608130000018ca390539000d5e434ebec1aa4d9020200da120000ef0c05ef00f0011505c800450105b5000ab600074233c2430d9c44000002f100011d311000c671b3000000018ca3905b6000d5e434ebec1aa4d9020200da120000ef0c05ef01f0011505c800450105b5000ab6000742354d430d9f44000002f100011d311000c671b3000000018ca3905f4800d5e434ebec1aa4d9020200da120000f00c05ef01f0001505c800450105b5000ab6000742356c430d9e44000002f100011d311000c671b3000000018ca3a4b26800d5e43178ec1aa0ae020700ef150006f00c05ef01f0011505c800450105b50008b60005423598430d9b44000002f100011d311000c671c3000000018ca3a4d97800d5e41bcaec1aa69b02050125150016000c05ef01f0011505c800450105b5000ab6000542356b430d9b44000002f100011d311000c671fa000000018ca3a5008800d5e40108ec1ab09102030125140019000c05ef01f0011505c800450105b5000bb600054235bc430d9b44000002f100011d311000c67240000000018ca3a5279800d5e3e56dec1abaeb0202012614001c000c05ef01f0011505c800450105b5000bb600054235b0430d9b44000002f100011d311000c67288000000018ca3a54ea800d5e3c2baec1ac7cf02000128140021000c05ef01f0011505c800450105b5000bb60005423574430d9b44000002f100011d311000c672e2000000018ca3a575b800d5e3a122ec1ad44f01fe0124140021000c05ef01f0011505c800450105b5000bb600054235b0430d9b44000002f100011d311000c67339000000018ca3a598e000d5e37e6eec1ae16501fe012515001c000c05ef01f0011505c800450105b5000ab6000542354d430d9b44000002f100011d311000c67394000000018ca3a5bff000d5e364c8ec1aead601ff012514000e000c05ef01f0011505c800450105b5000bb600054234fb430d9b44000002f100011d311000c673d6000000018ca3a5e70000d5e3541dec1af0e402000125150018000c05ef01f0011505c800450105b5000ab6000542356b430d9b44000002f100011d311000c67401000000018ca3a60e1000d5e33c7bec1af95a02000126150013000c05ef01f0011505c800450105b5000ab60005423579430d9b44000002f100011d311000c6743f000000018ca3a6352000d5e320d0ec1b03510200012515001c000c05ef01f0011505c800450105b5000ab600054235a3430d9b44000002f100011d311000c67486000000018ca3a65c3000d5e301d2ec1b0f080201012514001d000c05ef01f0011505c800450105b5000ab60005423547430d9b44000002f100011d311000c674d7000000018ca3a6834000d5e2e1dbec1b1b140201012714001e000c05ef01f0011505c800450105b5000ab600064235a7430d9b44000002f100011d311000c6752a000000018ca3a6aa5000d5e2c0b8ec1b281902000125140020000c05ef01f0011505c800450105b5000bb60006423577430d9b44000002f100011d311000c67581000000018ca3a6d16000d5e2a06dec1b34030200012513001c000c05ef01f0011505c800450105b5000bb600064235a7430d9b44000002f100011d311000c675d5000000018ca3a6f87000d5e27fe0ec1b40300200012613001f000c05ef01f0011505c800450105b5000bb60006423567430d9b44000002f100011d311000c6762a00130000331c";
        
        for (Object item : (List<?>) decoder.decode(null, null, binary(framesd))) {
            System.out.println(item);
                //verifyDecodedPosition(item, checkLocation, false, expected);
        }
`

And the result at the line decoder.decode gives me an IndexOutOfBoundException

java.lang.IndexOutOfBoundsException: readerIndex(1250) + length(16) exceeds writerIndex(1250): UnpooledHeapByteBuf(ridx: 1250, widx: 1250, cap: 1250/1250)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.readSlice(AbstractByteBuf.java:879)
	at org.traccar.protocol.TeltonikaProtocolDecoder.decodeLocation(TeltonikaProtocolDecoder.java:563)
	at org.traccar.protocol.TeltonikaProtocolDecoder.parseData(TeltonikaProtocolDecoder.java:653)
	at org.traccar.protocol.TeltonikaProtocolDecoder.decodeTcp(TeltonikaProtocolDecoder.java:698)
	at org.traccar.protocol.TeltonikaProtocolDecoder.decode(TeltonikaProtocolDecoder.java:686)
	at org.traccar.protocol.TeltonikaProtocolDecoderTest.testDecode(TeltonikaProtocolDecoderTest.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
