### ISSUE TITLE
MySQL migration (4.9) fails

### ISSUE THREAD

**Issue by libots** [traccar/traccar#4557]
**Describe the bug**
MySQL migration fails when upgrading docker image to 4.9 (from 4.8). Log shows errors and web UI is inaccessible. The database user has all privileges for the traccar database.

**Docker log**
```
Exception in thread "main" java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-4.9::changelog-4.9::author:
     Reason: liquibase.exception.DatabaseException: Can't create table `traccar`.`tc_events` (errno: 13 "Permission denied") [Failed SQL: (1005) CREATE INDEX event_deviceid_servertime ON traccar.tc_events(deviceid, servertime)]
	at org.traccar.Main.run(Main.java:163)
	at org.traccar.Main.main(Main.java:110)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-4.9::changelog-4.9::author:
     Reason: liquibase.exception.DatabaseException: Can't create table `traccar`.`tc_events` (errno: 13 "Permission denied") [Failed SQL: (1005) CREATE INDEX event_deviceid_servertime ON traccar.tc_events(deviceid, servertime)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:659)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:97)
	at liquibase.Liquibase.update(Liquibase.java:201)
	at liquibase.Liquibase.update(Liquibase.java:178)
	at liquibase.Liquibase.update(Liquibase.java:174)
	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:312)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:292)
	at org.traccar.Main.run(Main.java:137)
	... 1 more
Caused by: liquibase.exception.DatabaseException: Can't create table `traccar`.`tc_events` (errno: 13 "Permission denied") [Failed SQL: (1005) CREATE INDEX event_deviceid_servertime ON traccar.tc_events(deviceid, servertime)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:430)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:87)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:159)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1276)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1258)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:622)
	... 10 more
Caused by: java.sql.SQLException: Can't create table `traccar`.`tc_events` (errno: 13 "Permission denied")
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:426)
	... 15 more
```

**traccar.xml**
```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>
<properties>
    <entry key='config.default'>./conf/default.xml</entry>
    <entry key='filter.enable'>true</entry>
    <entry key='filter.zero'>true</entry>
    <entry key='database.driver'>com.mysql.cj.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://hostip:3306/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>user</entry>
    <entry key='database.password'>password</entry>
</properties>
```

**Comment by tananaev** [comment]
You say that user has all the permissions, but the error clearly says `"Permission denied"`.

**Comment by libots** [comment]
Indeed it does. To be safe, I just made sure, though:
```mysql
GRANT ALL PRIVILEGES ON `traccar`.* TO 'traccar'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'traccar'@'%';
```

Result: 2 rows

- GRANT USAGE ON *.* TO `traccar`@`%` IDENTIFIED BY PASSWORD '*...'
- GRANT ALL PRIVILEGES ON `traccar`.* TO `traccar`@`%` WITH GRANT OPTION

The error persists. Things seem to work fine if I go back to 4.8.

**Comment by tananaev** [comment]
Try logging in with the user and creating the table.

**Comment by libots** [comment]
Just tried running the query (`CREATE INDEX event_deviceid_servertime ON traccar.tc_events(deviceid, servertime)`) logged in as both the traccar and root user, same result (`errno: 13 "Permission denied"`). Strange. For what it's worth, I'm using MariaDB 10.4, also running in docker.

**Comment by tananaev** [comment]
This could be a file system permissions issue. Anyway, I'm going to close the ticket for now as it seems like the problem is with MariaDB, not Traccar server.

**Comment by libots** [comment]
Thanks for the help. I've got no idea what went wrong, but I just dropped all the tables and let Traccar recreate them, which worked fine. Fortunately it was easy enough to repopulate the data that mattered.
