### ISSUE TITLE
High CPU Usage after initial Connect

### ISSUE THREAD

**Issue by brunohpg** [traccar/traccar#5154]
**Describe the bug**

Hello,

I started to have a high CPU usage with Traccar that is preventing me from using other functionalities in the system (like stops).

I recently updated (2 months ago), however, we noticed the problem only in the last week.
Today I have updated to the lastest docker debian version and the problem persists.

The system is consuming 100% CPU even without receiving new packets.

When Traccar starts there is no excessive CPU consumption. However, when vehicles are connected, the CPU stuck at 100% and even when the vehicles are disconnected (blocking via firewall) the CPU remains at 100%.

I think it is related to receiving data, however, it is just the trigger of the problem.

I will attach information from jstack and pid of threads.
[stack.txt](https://github.com/traccar/traccar/files/12281775/stack.txt)
![traccar](https://github.com/traccar/traccar/assets/4167545/30337749-433a-482e-96cf-5a3019d2d0df)

Threads 40 (nid=0x28), 43 (nid=2b) and 44 (nid=2c) are the main problem. It's in:

```
"nioEventLoopGroup-3-5" #29 prio=10 os_prio=0 cpu=433443.45ms elapsed=835.32s tid=0x00007f4f55a70000 nid=0x2c runnable  [0x00007f4ec76f3000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(java.base@11.0.16/Unknown Source)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(java.base@11.0.16/Unknown Source)
	at org.traccar.session.cache.CacheManager.getObject(CacheManager.java:102)
	at org.traccar.helper.model.AttributeUtil$CacheProvider.getGroup(AttributeUtil.java:130)
	at org.traccar.helper.model.AttributeUtil.lookup(AttributeUtil.java:55)
	at org.traccar.helper.model.AttributeUtil.lookup(AttributeUtil.java:46)
	at org.traccar.handler.MotionHandler.handlePosition(MotionHandler.java:43)
	at org.traccar.BaseDataHandler.channelRead(BaseDataHandler.java:27)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.traccar.handler.GeocoderHandler.channelRead(GeocoderHandler.java:81)
```

I use 5001 and 5013 ports in Docker environment. But I desactived 5013 and the system still 100%.

There's nothing special in configurations and I don't use addicional attributes or geofences.

Ty.

**Expected behavior**
Normal CPU when idle.

**Desktop (please complete the following information):**
 - OS: Host and Docker: Debian 11 (bullseye)
 - Browser Chrome

**Comment by tananaev** [comment]
1. What's your hardware specs?
2. What are the Traccar memory limits?
3. How many devices and connection do you have?
4. What do you have linked to devices?

**Comment by brunohpg** [comment]
**Hardware**

CPU: Quadcore Intel(R) Xeon(R) CPU E5410  @ 2.33GHz
12GB RAM

**Traccar Memory**

Default 1GB.

**Devices**

71 devices registered, but only 50 really active (I mean, connections).

**Linked to Devices**

We basically use position. A few devices has ignition sensor. 

We don't link anything else to devices, like geofences, notifications, attributes, ...

We use Groups do show the devices do the users. Rarelly we link user to device.

** New Stack / Log **

I'm testing, then I have new threads and stack trace:
![traccar2](https://github.com/traccar/traccar/assets/4167545/65c81236-3290-478b-960f-2a7fa8489845)
[stack2.txt](https://github.com/traccar/traccar/files/12282477/stack2.txt)

After stop the connections I found this error:

```
2023-08-07 15:55:15  WARN: Device 28 cache missing
2023-08-07 15:55:15  WARN: Device 80 cache missing
2023-08-07 15:55:15  WARN: Device 58 cache missing
2023-08-07 15:55:15  WARN: Device 30 cache missing
2023-08-07 15:55:15  INFO: [T2db07f95] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
2023-08-07 15:55:15  INFO: [T94802d54] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
2023-08-07 15:55:15  INFO: [T5bd8efd7] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
2023-08-07 15:55:15  INFO: [T0375e176] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
2023-08-07 15:55:15  INFO: [T92abd17a] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
2023-08-07 15:55:15  INFO: [T18408a7b] error - NullPointerException (MainEventHandler:105 < ... < BaseDataHandler:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:81 < ...)
```

I'm cheking the stack, all threads are "stuck" in shared lock.

Waiting for locks should not use CPU, then it's served so fast we can check the code are executed.

**Comment by tananaev** [comment]
Does it happen when you do some changes, like adding a new device or adding a device to a group?

**Comment by brunohpg** [comment]
We have change some groups weeks ago. I'll check all groups.

I think the problem is here:
https://github.com/traccar/traccar/blob/36d319a81dc3d2c12222cce012c1a1a307a865b2/src/main/java/org/traccar/helper/model/AttributeUtil.java#L53-L62

If the groups exists and has no `ConfigKey key` the loop never ends.

**Comment by tananaev** [comment]
Why would it never end?

**Comment by brunohpg** [comment]
```
 long groupId = device.getGroupId();  // here we have a group id, due device have a group.
 while (result == null && groupId > 0) { 
     Group group = provider.getGroup(groupId); // here we have Group object (ok! group exists)
     if (group != null) { 
         result = group.getAttributes().get(key.getKey()); // as group exists and group.getAttributes() is a Map, if the key Keys.EVENT_MOTION_SPEED_THRESHOLD it will return null
         groupId = group.getGroupId();  // here we set groupId  as same value
     } else { 
         groupId = 0; // Never reach
     } 
 } 
```

The `result` always `null` if the `group.getAttributes()` Map does not have the entry for `Keys.EVENT_MOTION_SPEED_THRESHOLD`.

The `groupId` always have same value.

The condition `result == null && groupId > 0` always are satisfied then the loop nevers ends.

I think should be a `break´ after `groupId = group.getGroupId();`.

**Comment by brunohpg** [comment]
Should `groupId = group.getGroupId();` get parent group id? Or something like it.

**Comment by brunohpg** [comment]
I have moved all devices to the same group and CPU sill stuck in 100%.

Then I have configured `event.motion.speedThreshold` attribute in group and CPU now are in low usage. :)

**Comment by tananaev** [comment]
The `group.getGroupId()` gives the parent group, so there's no infinite loop there.

**Comment by brunohpg** [comment]
Hum... I think someone has configured parent in loop.

**Comment by brunohpg** [comment]
Maybe miss configuration.
