### ISSUE TITLE
Error updating to 5.9 from 5.8

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [traccar/traccar#5164]
**Describe the bug**
I've downloaded the amd64 build, extracted, run the .run, and got error while trying to start traccar.

**To Reproduce**
1. install 5.8 i assume, although i started at 5.5
2. update to 5.9, download, extract, stop traccar, run .run, start traccar

**Expected behavior**
Workng like it used to on 5.8

**Screenshots**
Better, i got logs
```
Sep 02 22:58:31 traccar systemd[1]: Started traccar.
Sep 02 22:58:35 traccar traccar[12031]: Exception in thread "main" java.lang.RuntimeException: com.google.inject.ProvisionException: Unable to provision, see the following errors:
Sep 02 22:58:35 traccar traccar[12031]: 1) [Guice/ErrorInCustomProvider]: HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported database file version or invalid file header in file "/opt/traccar/data/database.mv.db" [90048-220]
Sep 02 22:58:35 traccar traccar[12031]:   at DatabaseModule.provideDataSource(DatabaseModule.java:46)
Sep 02 22:58:35 traccar traccar[12031]:   at DatabaseStorage.<init>(DatabaseStorage.java:48)
Sep 02 22:58:35 traccar traccar[12031]:       \_ for 2nd parameter
Sep 02 22:58:35 traccar traccar[12031]:   while locating DatabaseStorage
Sep 02 22:58:35 traccar traccar[12031]:   at MainModule.provideStorage(MainModule.java:123)
Sep 02 22:58:35 traccar traccar[12031]:   while locating Storage
Sep 02 22:58:35 traccar traccar[12031]: Learn more:
Sep 02 22:58:35 traccar traccar[12031]:   https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Sep 02 22:58:35 traccar traccar[12031]: 1 error
Sep 02 22:58:35 traccar traccar[12031]: ======================
Sep 02 22:58:35 traccar traccar[12031]: Full classname legend:
Sep 02 22:58:35 traccar traccar[12031]: ======================
Sep 02 22:58:35 traccar traccar[12031]: DatabaseModule:                         "org.traccar.storage.DatabaseModule"
Sep 02 22:58:35 traccar traccar[12031]: DatabaseStorage:                        "org.traccar.storage.DatabaseStorage"
Sep 02 22:58:35 traccar traccar[12031]: HikariPool$PoolInitializationException: "com.zaxxer.hikari.pool.HikariPool$PoolInitializationException"
Sep 02 22:58:35 traccar traccar[12031]: MainModule:                             "org.traccar.MainModule"
Sep 02 22:58:35 traccar traccar[12031]: Storage:                                "org.traccar.storage.Storage"
Sep 02 22:58:35 traccar traccar[12031]: ========================
Sep 02 22:58:35 traccar traccar[12031]: End of classname legend:
Sep 02 22:58:35 traccar traccar[12031]: ========================
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.Main.run(Main.java:154)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.Main.main(Main.java:114)
Sep 02 22:58:35 traccar traccar[12031]: Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
Sep 02 22:58:35 traccar traccar[12031]: 1) [Guice/ErrorInCustomProvider]: HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported database file version or invalid file header in file "/opt/traccar/data/database.mv.db" [90048-220]
Sep 02 22:58:35 traccar traccar[12031]:   at DatabaseModule.provideDataSource(DatabaseModule.java:46)
Sep 02 22:58:35 traccar traccar[12031]:   at DatabaseStorage.<init>(DatabaseStorage.java:48)
Sep 02 22:58:35 traccar traccar[12031]:       \_ for 2nd parameter
Sep 02 22:58:35 traccar traccar[12031]:   while locating DatabaseStorage
Sep 02 22:58:35 traccar traccar[12031]:   at MainModule.provideStorage(MainModule.java:123)
Sep 02 22:58:35 traccar traccar[12031]:   while locating Storage
Sep 02 22:58:35 traccar traccar[12031]: Learn more:
Sep 02 22:58:35 traccar traccar[12031]:   https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Sep 02 22:58:35 traccar traccar[12031]: 1 error
Sep 02 22:58:35 traccar traccar[12031]: ======================
Sep 02 22:58:35 traccar traccar[12031]: Full classname legend:
Sep 02 22:58:35 traccar traccar[12031]: ======================
Sep 02 22:58:35 traccar traccar[12031]: DatabaseModule:                         "org.traccar.storage.DatabaseModule"
Sep 02 22:58:35 traccar traccar[12031]: DatabaseStorage:                        "org.traccar.storage.DatabaseStorage"
Sep 02 22:58:35 traccar traccar[12031]: HikariPool$PoolInitializationException: "com.zaxxer.hikari.pool.HikariPool$PoolInitializationException"
Sep 02 22:58:35 traccar traccar[12031]: MainModule:                             "org.traccar.MainModule"
Sep 02 22:58:35 traccar traccar[12031]: Storage:                                "org.traccar.storage.Storage"
Sep 02 22:58:35 traccar traccar[12031]: ========================
Sep 02 22:58:35 traccar traccar[12031]: End of classname legend:
Sep 02 22:58:35 traccar traccar[12031]: ========================
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.Main.run(Main.java:126)
Sep 02 22:58:35 traccar traccar[12031]:         ... 1 more
Sep 02 22:58:35 traccar traccar[12031]: Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported database file version or invalid file header in file "/opt/traccar/data/database.mv.db" [90048-220]
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.storage.DatabaseModule.provideDataSource(DatabaseModule.java:79)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.storage.DatabaseModule$$FastClassByGuice$$1da279.GUICE$TRAMPOLINE(<generated>)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.storage.DatabaseModule$$FastClassByGuice$$1da279.apply(<generated>)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.MainModule.provideStorage(MainModule.java:126)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.MainModule$$FastClassByGuice$$ecb8b.GUICE$TRAMPOLINE(<generated>)
Sep 02 22:58:35 traccar traccar[12031]:         at org.traccar.MainModule$$FastClassByGuice$$ecb8b.apply(<generated>)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
Sep 02 22:58:35 traccar traccar[12031]:         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
Sep 02 22:58:35 traccar traccar[12031]:         ... 3 more
Sep 02 22:58:35 traccar traccar[12031]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/opt/traccar/data/database.mv.db" [90048-220]
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.message.DbException.get(DbException.java:212)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:158)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.db.Store.<init>(Store.java:142)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.engine.Database.<init>(Database.java:324)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.engine.Engine.openSession(Engine.java:92)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.engine.Engine.openSession(Engine.java:222)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.engine.Engine.createSession(Engine.java:201)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.Driver.connect(Driver.java:59)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
Sep 02 22:58:35 traccar traccar[12031]:         at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
Sep 02 22:58:35 traccar traccar[12031]:         ... 33 more
Sep 02 22:58:35 traccar traccar[12031]: Caused by: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.220/5]
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:944)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.FileStore.start(FileStore.java:917)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.MVStore.<init>(MVStore.java:289)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2036)
Sep 02 22:58:35 traccar traccar[12031]:         at org.h2.mvstore.db.Store.<init>(Store.java:133)
Sep 02 22:58:35 traccar traccar[12031]:         ... 45 more
Sep 02 22:58:35 traccar systemd[1]: traccar.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 22:58:35 traccar systemd[1]: traccar.service: Failed with result 'exit-code'.
```

**Desktop (please complete the following information):**
not applicable but i will put server OS
 - OS: opensuse Tumbleweed
 - Browser n/a
 - Version latest

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Comment by tananaev** [comment]
The H2 format is not compatible. You have to migrate the database to the new version manually.

**Comment by Michal-Szczepaniak** [comment]
yes but how.

**Comment by tananaev** [comment]
If you want to continue refusing our recommendation and use H2, you should probably check their documentation for the migration details. You probably need to export the database and then import with the new version.

**Comment by Michal-Szczepaniak** [comment]
Your recommendation? I didn't choose H2, traccar did. Can i migrate to something else? Maybe i configured it wrong while installing i didn't know about refusing anything or choosing anything

**Comment by tananaev** [comment]
Please read the official documentation and the forum before asking any more questions.

Also, GitHub issues are reserved only for bugs and feature requests. For discussions your should use the forum.

**Comment by Michal-Szczepaniak** [comment]
Yeah fair

**Comment by kczeladko** [comment]
@Michal-Szczepaniak 
get h2 jars in version related to old docker image 5.8 (h2-2.1.214.jar) and new docker version 5.9 (h2-2.2.220.jar)
stop container
locate your traccar h2 db file  "database.mv.db" and backup it then execute dump to backup.zip, inspect backup.zip as this is just sql script, then restore from backup with new h2 version to new db "database-new" where file name is "database-new.mv.db" 
```
kcz@hp800g4:~/docker-compose/traccar/data/backup$ java -cp h2-2.1.214.jar org.h2.tools.Script -url jdbc:h2:./database -user sa -script ./backup.zip -options compression zip
kcz@hp800g4:~/docker-compose/traccar/data/backup$ java -cp h2-2.2.220.jar org.h2.tools.RunScript -url jdbc:h2:./database-new -user sa -script ./backup.zip -options compression zip
```
rewrite old db file with new, start container with 5.9

**Comment by Michal-Szczepaniak** [comment]
oh ye and about refusing the recommendation.

there's nothing in documentation about h2 https://www.traccar.org/linux/
and it's also default https://www.traccar.org/mysql/
