### ISSUE TITLE
Linking Home Assistant to external server not working

### ISSUE THREAD

**Issue by pkkrusty** [traccar/traccar#5252]
**Describe the bug**
Set up my traccar server in configuration.yaml as follows, following documentation:
```
device_tracker:
  - platform: traccar
    host: traccar.my.domain
    port: 8082
    username: user
    password: password
```
Error seen in the logs:
```
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:307 
Integration: Device tracker (documentation, issues) 
First occurred: 8:27:02 PM (1 occurrences) 
Last logged: 8:27:02 PM

Error setting up platform legacy traccar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 307, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/traccar/device_tracker.py", line 202, in async_setup_scanner
    return await scanner.async_init()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/traccar/device_tracker.py", line 238, in async_init
    await self._api.get_server()
  File "/usr/local/lib/python3.12/site-packages/pytraccar/client.py", line 92, in get_server
    response: ServerModel = await self._call_api("server")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytraccar/client.py", line 78, in _call_api
    raise TraccarResponseException(f"{response.status}: {response.reason}")
pytraccar.exceptions.TraccarResponseException: 400: Bad Request
```
I can connect to the traccar server no problem by going to the url directly

**To Reproduce**

**Expected behavior**
HA can connect to traccar server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [safari]
 - Version [16.1]

**Additional context**

**Comment by tananaev** [comment]
That's not a Traccar bug. We don't have any official integration with HA.
